/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.evomaster.client.java.controller.mongo.dsl.MongoDsl.mongo;
import  org.evomaster.client.java.controller.api.dto.database.operations.MongoInsertionResultsDto;
import  org.evomaster.client.java.controller.api.dto.database.operations.MongoInsertionDto;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-06-08T17:09:38.911939229+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 21 tests
 * <br>
*  Covered targets: 116
 * <br>
*  Used time: 0h 20m 38s
 * <br>
*  Needed budget for current results: 95%
 * <br>
*  
*/
public class EM_bibliothek_True_25_false_false_SPECIFIED_false_0_Test {

    
    private static final SutHandler controller = new em.external.bibliothek.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "bibliothek-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exp/exec/bibliothek__wbMultiGiven__10010__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_17"));
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (200) GET:/openapi
    */
    @Test @Timeout(60)
    public void test_0_getOnOpenapiReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/openapi")
                .then()
                .statusCode(200);
    }
    
    
    /**
    * Calls:
    * (200) GET:/v2/projects
    */
    @Test @Timeout(60)
    public void test_1_getOnProjectsReturnsObject() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'projects'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}
    */
    @Test @Timeout(60)
    public void test_2_getOnV2ProjectReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/iw")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_3_getOnV2ProjectWithQueryParamReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper?EMextraParam123=_EM_17_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
    }
    
    
    /**
    * Calls:
    * (400) GET:/v2/projects/{project}/versions/{version}
    */
    @Test @Timeout(60)
    public void test_4_getOnVersionReturns400() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_llr_postfix/versions/9%5CLwWh7URU3")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}
    */
    @Test @Timeout(60)
    public void test_5_getOnProjectVersionWithQueryParamReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_e_postfix/versions/_EM_4_XYZ_?EMextraParam123=_EM_5_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/version_group/{family}
    */
    @Test @Timeout(60)
    public void test_6_getOnProjectVersion_groupWithQueryParamReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/oba/version_group/_EM_6_XYZ_?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_7_getOnVersionReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper/versions/_EM_32_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/version_group/{family}
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_8_getOnProjectVersion_groupReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper/version_group/QMK")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}
    */
    @Test @Timeout(60)
    public void test_9_getOnVersionReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/exc/versions/42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}/builds
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_10_getOnVersionBuildsWithQueryParamReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper/versions/_EM_1_XYZ_/builds?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/version_group/{family}/builds
    */
    @Test @Timeout(60)
    public void test_11_getOnBuildsReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_byq_postfix/version_group/X/builds?EMextraParam123=_EM_3_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/version_group/{family}/builds
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_12_getOnBuildsReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_102_XYZ_")
                .get(baseUrlOfSut + "/v2/projects/paper/version_group/bMc_1sF/builds?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}/builds
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_13_getOnVersionBuildsReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper/versions/42/builds")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}
    */
    @Test @Timeout(60)
    public void test_14_getOnVersionBuildWithQueryParamReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/rto_postfix/versions/bWRRSvf/builds/955016554?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_15_getOnVersionBuildReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper/versions/42/builds/605")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
    }
    
    
    /**
    * Calls:
    * 1 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}
    * 2 - (404) GET:/v2/projects/{project}
    * 3 - (200) GET:/v2/projects
    * 4 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 5 - (404) GET:/v2/projects/{project}/version_group/{family}/builds
    * 6 - (200) GET:/v2/projects
    * 7 - (404) GET:/v2/projects/{project}/version_group/{family}
    * 8 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}
    * 9 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 10 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 11 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 12 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 13 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 14 - (404) GET:/v2/projects/{project}/version_group/{family}/builds
    * 15 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 16 - (404) GET:/v2/projects/{project}/version_group/{family}/builds
    * 17 - (404) GET:/v2/projects/{project}/versions/{version}/builds
    * 18 - (404) GET:/v2/projects/{project}
    * 19 - (404) GET:/v2/projects/{project}
    * 20 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_16_getOnBuildDownloadReturns404UsingMongo() throws Exception {
        List<MongoInsertionDto> insertions = mongo().insertInto("library", "projects")
                .d("{\"name\":\"5ma8Qm8\", \"friendlyName\":\"4Ha\", \"_id\":{\"$oid\":\"367094ba53f1bc8a07d8baa7\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"uFL0\", \"friendlyName\":\"puHB9\", \"_id\":{\"$oid\":\"e4fa799d5ed128f14a4ad0c1\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"_EM_83_XYZ_\", \"friendlyName\":\"eFGNIlV4\", \"_id\":{\"$oid\":\"e2b2bedcddfe3af49e5db87c\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"qAncOeknM\", \"friendlyName\":\"rSjlVtAt\", \"_id\":{\"$oid\":\"efa02aceec109a4a5a01ec7b\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"QAjv52mqDa9SSd5\", \"friendlyName\":\"EOWIMLfk28kXYEI\", \"_id\":{\"$oid\":\"8cd6c8b738abba90ff91d464\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"6LZ6kBJUW0LZ8jI\", \"friendlyName\":\"QI61lyZb7zy0C\", \"_id\":{\"$oid\":\"a6bc5d7c88c312f6cf1a5fb8\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"q7IjvEc2bLfCXDz3\", \"friendlyName\":\"KxvIAAPRAGNn\", \"_id\":{\"$oid\":\"de163ccaeb7dbf50d839fb6f\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"bgqHqPV\", \"friendlyName\":\"|3\", \"_id\":{\"$oid\":\"7eb6129dfedd2e1e390c2f5a\"}}")
            .dtos();
        MongoInsertionResultsDto insertionsresult = controller.execInsertionsIntoMongoDatabase(insertions);
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/prefix_v/versions/OwlG2w0if/builds/386")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'projects'.size()", equalTo(8))
                .body("'projects'", hasItems("5ma8Qm8", "uFL0", "_EM_83_XYZ_", "qAncOeknM", "QAjv52mqDa9SSd5", "6LZ6kBJUW0LZ8jI", "q7IjvEc2bLfCXDz3", "bgqHqPV"));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/prefix_rwk/versions/_EM_51_XYZ_/builds/824/downloads/.e-?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_c_postfix/version_group/_EM_52_XYZ_/builds")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'projects'.size()", equalTo(8))
                .body("'projects'", hasItems("5ma8Qm8", "uFL0", "_EM_83_XYZ_", "qAncOeknM", "QAjv52mqDa9SSd5", "6LZ6kBJUW0LZ8jI", "q7IjvEc2bLfCXDz3", "bgqHqPV"));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/ama/version_group/=x3h")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/zdl/versions/zF92IIEeJn82M0Ur/builds/770")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_56_XYZ_")
                .get(baseUrlOfSut + "/v2/projects/prefix_tzu_postfix/versions/07dQ7qdf6Dy/builds/1048765/downloads/9_postfix?EMextraParam123=_EM_55_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_c/versions/N1WUfqGheVN/builds/-1/downloads/9s._postfix?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/bac_postfix/versions/xLbeFAhuh9/builds/33278/downloads/prefix_7_postfix?EMextraParam123=_EM_58_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_59_XYZ_")
                .get(baseUrlOfSut + "/v2/projects/prefix_c/versions/a5spSlIcqF/builds/455/downloads/-._postfix")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_op/versions/_EM_60_XYZ_/builds/245/downloads/.-_?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/by_postfix/version_group/lvfqbygWW'ZxAAL/builds?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_jki_postfix/versions/X_hXttjzyi1Q/builds/125/downloads/prefix_I-r_postfix?EMextraParam123=_EM_64_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper/version_group/e3CGp2Z8/builds?EMextraParam123=_EM_65_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/ur/versions/_EM_84_XYZ_/builds")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_68_XYZ_")
                .get(baseUrlOfSut + "/v2/projects/b?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_klk?EMextraParam123=_EM_69_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/z/versions/_EM_85_XYZ_/builds/504/downloads/prefix_7r._postfix")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * 1 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}
    * 2 - (404) GET:/v2/projects/{project}
    * 3 - (200) GET:/v2/projects
    * 4 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 5 - (404) GET:/v2/projects/{project}/version_group/{family}/builds
    * 6 - (200) GET:/v2/projects
    * 7 - (404) GET:/v2/projects/{project}/version_group/{family}
    * 8 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}
    * 9 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 10 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 11 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 12 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 13 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 14 - (404) GET:/v2/projects/{project}/version_group/{family}/builds
    * 15 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * 16 - (404) GET:/v2/projects/{project}/version_group/{family}/builds
    * 17 - (404) GET:/v2/projects/{project}/versions/{version}/builds
    * 18 - (404) GET:/v2/projects/{project}
    * 19 - (404) GET:/v2/projects/{project}
    * 20 - (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_17_getOnBuildDownloadWithQueryParamReturns404UsingMongo() throws Exception {
        List<MongoInsertionDto> insertions = mongo().insertInto("library", "projects")
                .d("{\"name\":\"5ma8Qm8\", \"friendlyName\":\"4Ha\", \"_id\":{\"$oid\":\"367094ba53f1bc8a07d8baa7\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"uFL0\", \"friendlyName\":\"puHB9\", \"_id\":{\"$oid\":\"e4fa799d5ed128f14a4ad0c1\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"_EM_83_XYZ_\", \"friendlyName\":\"eFGNIlV4\", \"_id\":{\"$oid\":\"e2b2bedcddfe3af49e5db87c\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"qAncOeknM\", \"friendlyName\":\"rSjlVtAt\", \"_id\":{\"$oid\":\"efa02aceec109a4a5a01ec7b\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"QAjv52mqDa9SSd5\", \"friendlyName\":\"EOWIMLfk28kXYEI\", \"_id\":{\"$oid\":\"8cd6c8b738abba90ff91d464\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"6LZ6kBJUW0LZ8jI\", \"friendlyName\":\"QI61lyZb7zy0C\", \"_id\":{\"$oid\":\"a6bc5d7c88c312f6cf1a5fb8\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"q7IjvEc2bLfCXDz3\", \"friendlyName\":\"KxvIAAPRAGNn\", \"_id\":{\"$oid\":\"de163ccaeb7dbf50d839fb6f\"}}")
            .and().insertInto("library", "projects")
                .d("{\"name\":\"bgqHqPV\", \"friendlyName\":\"|3\", \"_id\":{\"$oid\":\"7eb6129dfedd2e1e390c2f5a\"}}")
            .dtos();
        MongoInsertionResultsDto insertionsresult = controller.execInsertionsIntoMongoDatabase(insertions);
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_v/versions/OwlG2w0if/builds/-2096766?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/d")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects?EMextraParam123=_EM_49_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'projects'.size()", equalTo(8))
                .body("'projects'", hasItems("5ma8Qm8", "uFL0", "_EM_83_XYZ_", "qAncOeknM", "QAjv52mqDa9SSd5", "6LZ6kBJUW0LZ8jI", "q7IjvEc2bLfCXDz3", "bgqHqPV"));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/prefix_rwk/versions/_EM_51_XYZ_/builds/828/downloads/.d_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_c_postfix/version_group/_EM_52_XYZ_/builds")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'projects'.size()", equalTo(8))
                .body("'projects'", hasItems("5ma8Qm8", "uFL0", "_EM_83_XYZ_", "qAncOeknM", "QAjv52mqDa9SSd5", "6LZ6kBJUW0LZ8jI", "q7IjvEc2bLfCXDz3", "bgqHqPV"));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/bma/version_group/_EM_116_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/zdl/versions/zF92IIEeJn82M0UrG/builds/770")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_56_XYZ_")
                .get(baseUrlOfSut + "/v2/projects/prefix_tau_postfix/versions/_EM_117_XYZ_/builds/1048765/downloads/9_postfix?EMextraParam123=_EM_55_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_57_XYZ_")
                .get(baseUrlOfSut + "/v2/projects/prefix_c/versions/N1WUfqGheVNP/builds/-1/downloads/9s._postfix")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/bac_postfix/versions/xLbeFAxuh9/builds/33278/downloads/prefix_7_postfix?EMextraParam123=_EM_58_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_d/versions/_EM_118_XYZ_/builds/-16776761/downloads/-__postfix?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_op/versions/_EM_119_XYZ_/builds/245/downloads/9a_?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_63_XYZ_")
                .get(baseUrlOfSut + "/v2/projects/paper/version_group/lvfqbygWW'ZxAALg/builds")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/prefix_jki_postfix/versions/X_hXttjzyi1Q/builds/133/downloads/prefix_Iar_postfix")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/prefix_pwu_postfix/version_group/U3CGp2Z8/builds")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/ur/versions/PomuEGs/builds?EMextraParam123=_EM_67_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/a?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Project not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/prefix_klk")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/z/versions/k2ft_/builds/1528/downloads/prefix_7r._postfix?EMextraParam123=_EM_70_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    */
    @Test @Timeout(60)
    public void test_18_getOnDownloadReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/i_postfix/versions/HVASdzFEVnIBj/builds/23/downloads/--?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    * Using 1 example:
    *   (-) PATH: project -> paper
    */
    @Test @Timeout(60)
    public void test_19_getOnBuildDownloadReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/projects/paper/versions/_EM_13_XYZ_/builds/67108887/downloads/--")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }
    
    
    /**
    * Calls:
    * (404) GET:/v2/projects/{project}/versions/{version}/builds/{build}/downloads/{download}
    */
    @Test @Timeout(60)
    public void test_20_getOnDownloadReturns404() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/v2/projects/prefix_zc/versions/QLKaSlPiDEv1jP/builds/-1048496/downloads/U_postfix?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'error'", containsString("Endpoint not found."));
    }


}
