/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-04T13:22:53.648090815+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 5 tests
 * <br>
*  Covered targets: 50
 * <br>
*  Used time: 1h 0m 31s
 * <br>
*  Needed budget for current results: 31%
 * <br>
*  
*/
public class EM_cwa_verification_False_6_Test {

    
    private static final SutHandler controller = new em.external.app.coronawarn.verification.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "cwa-verification-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exec/cwa-verification__wbEnabledFlakiness__10080__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_11"));
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetDatabase(Arrays.asList());
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (406) POST:/version/v1/testresult
    */
    @Test @Timeout(60)
    public void test_0_postOnTestresultReturns406() throws Exception {
        
        given().accept("*/*")
                .header("cwa-fake", "E_Ky")
                .header("x-EMextraHeader123", "42")
                .header("X-B3-Flags", "_EM_64_XYZ_")
                .header("X-B3-TraceId", "9UnBfuBrG1s6px6")
                .contentType("application/json")
                .body(" { " + 
                    " \"registrationToken\": \"bbc3084c-d07d-4d46-aa6e-9c7ea0f8de27\" " + 
                    " } ")
                .post(baseUrlOfSut + "/version/v1/testresult?EMextraParam123=_EM_62_XYZ_")
                .then()
                .statusCode(406)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (406) POST:/version/v1/tan
    */
    @Test @Timeout(60)
    public void test_1_postOnTanReturns406() throws Exception {
        
        given().accept("*/*")
                .header("cwa-fake", "Iy")
                .header("x-EMextraHeader123", "42")
                .header("b3", "_EM_206_XYZ_")
                .header("X-B3-Flags", "_EM_207_XYZ_")
                .contentType("application/json")
                .body(" { " + 
                    " \"registrationToken\": \"bdeeaa6c-b3fa-40d1-8ffd-f58ea76cffcf\", " + 
                    " \"responsePadding\": \"LP1xw\" " + 
                    " } ")
                .post(baseUrlOfSut + "/version/v1/tan?EMextraParam123=42")
                .then()
                .statusCode(406)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (406) POST:/version/v1/registrationToken
    */
    @Test @Timeout(60)
    public void test_2_postOnRegistrationTokenReturns406() throws Exception {
        
        given().accept("*/*")
                .header("cwa-fake", "y4a")
                .header("x-EMextraHeader123", "")
                .header("X-B3-Flags", "_EM_581_XYZ_")
                .header("X-B3-TraceId", "zqiBFyNhsFpHO")
                .contentType("application/json")
                .body(" { " + 
                    " \"key\": \"9m1L8YfFoias\" " + 
                    " } ")
                .post(baseUrlOfSut + "/version/v1/registrationToken?EMextraParam123=42")
                .then()
                .statusCode(406)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (406) POST:/version/v1/tan/teletan
    */
    @Test @Timeout(60)
    public void test_3_postOnTeletanReturns406() throws Exception {
        
        given().accept("*/*")
                .header("Authorization", "{\"token\":\"_EM_204_XYZ_\"}")
                .header("x-EMextraHeader123", "_EM_203_XYZ_")
                .header("X-B3-Flags", "_EM_205_XYZ_")
                .post(baseUrlOfSut + "/version/v1/tan/teletan")
                .then()
                .statusCode(406)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (406) POST:/version/v1/tan/verify
    */
    @Test @Timeout(60)
    public void test_4_postOnVerifyReturns406() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("b3", "kdZYIv")
                .header("X-B3-Flags", "_EM_1341_XYZ_")
                .header("X-B3-TraceId", "UlPR")
                .contentType("application/json")
                .body(" { " + 
                    " \"tan\": \"c16916c6-8e50-4c90-b3ac-f5c48e579b5e\" " + 
                    " } ")
                .post(baseUrlOfSut + "/version/v1/tan/verify")
                .then()
                .statusCode(406)
                .assertThat()
                .body(isEmptyOrNullString());
    }


}
