/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-04T19:02:05.113592750+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 21 tests
 * <br>
*  Covered targets: 239
 * <br>
*  Used time: 1h 1m 1s
 * <br>
*  Needed budget for current results: 79%
 * <br>
*  
*/
public class EM_erc20_rest_service_True_6_Test {

    
    private static final SutHandler controller = new em.external.erc20restservice.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "erc20-rest-service-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exec/erc20-rest-service__wbEnabledFlakiness__10090__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_8"));
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (500) POST:/deploy
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_0_postOnDeployShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/ContractService_54_deploy
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/deploy'.
        given().accept("*/*")
                .header("privateFor", "MswjV")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"decimalUnits\": 163, " + 
                    " \"initialAmount\": 104, " + 
                    " \"tokenName\": \"X_3rzBSK_R3mH_x7\", " + 
                    " \"tokenSymbol\": \"\" " + 
                    " } ")
                .post(baseUrlOfSut + "/deploy")
                .then()
                .statusCode(500)// io/blk/erc20/ContractService_54_deploy
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/deploy"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/deploy
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_1_postOnDeployShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_293_deploy
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/deploy'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"tokenName\": \"_EM_23_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/deploy")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_293_deploy
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No message available"))
                .body("'path'", containsString("/deploy"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/deploy
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_2_postOnDeployShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_293_deploy
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/deploy'.
        given().accept("*/*")
                .header("privateFor", "_EM_429_XYZ_")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"decimalUnits\": 123, " + 
                    " \"initialAmount\": 843 " + 
                    " } ")
                .post(baseUrlOfSut + "/deploy")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_293_deploy
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("No message available"))
                .body("'path'", containsString("/deploy"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/config
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_3_getOnConfigReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type [Path '/fromAddress'] Instance type (null) does not match any allowed primitive type (allowed: ["string"])
        given().accept("application/json;charset=UTF-8")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/config")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'nodeEndpoint'", nullValue())
                .body("'fromAddress'", nullValue());
    }
    
    
    /**
    * Calls:
    * (500) GET:/{contractAddress}/allowance
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_4_getOnAllowanceShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/allowance'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/63grVTnDbMcEit/allowance?" + 
                    "ownerAddress=_EM_3_XYZ_&" + 
                    "spenderAddress=_EM_4_XYZ_")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/63grVTnDbMcEit/allowance"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/{contractAddress}/decimals
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_5_getOnDecimalsShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/decimals'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/_EM_6_XYZ_/decimals?EMextraParam123=_EM_7_XYZ_")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/_EM_6_XYZ_/decimals"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/{contractAddress}/name
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_6_getOnNameShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/name'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/aJo/name?EMextraParam123=42")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/aJo/name"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/{contractAddress}/symbol
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_7_getOnSymbolShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/symbol'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/RoV5O2EgrJ_uNOji/symbol?EMextraParam123=_EM_9_XYZ_")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/RoV5O2EgrJ_uNOji/symbol"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/{contractAddress}/totalSupply
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_8_getOnTotalSupplyShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/totalSupply'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/_EM_11_XYZ_/totalSupply?EMextraParam123=42")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/_EM_11_XYZ_/totalSupply"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/{contractAddress}/version
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_9_getOnVersionShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/version'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/yzJojWpF4pisdQo/version")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/yzJojWpF4pisdQo/version"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/{contractAddress}/transferFrom
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_10_postOnTransferFromShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/transferFrom'.
        given().accept("*/*")
                .header("privateFor", "X96U7kXU35OFMZi")
                .header("x-EMextraHeader123", "42")
                .contentType("application/json")
                .body(" { " + 
                    " \"from\": \"_EM_21_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/Rtvn9mMh8uq6eXJ/transferFrom?EMextraParam123=_EM_22_XYZ_")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/Rtvn9mMh8uq6eXJ/transferFrom"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/{contractAddress}/approve
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_11_postOnApproveShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/approve'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"value\": 145 " + 
                    " } ")
                .post(baseUrlOfSut + "/bG/approve?EMextraParam123=_EM_14_XYZ_")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/bG/approve"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/{contractAddress}/approveAndCall
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_12_postOnApproveAndCallShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/approveAndCall'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_18_XYZ_")
                .contentType("application/json")
                .body(" { " + 
                    " \"EM_tainted_map\": \"_EM_1_XYZ_\" " + 
                    " } ")
                .post(baseUrlOfSut + "/_EM_15_XYZ_/approveAndCall")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/_EM_15_XYZ_/approveAndCall"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/{contractAddress}/transfer
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_13_postOnTransferShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/transfer'.
        given().accept("*/*")
                .header("privateFor", "RZt")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"value\": 320 " + 
                    " } ")
                .post(baseUrlOfSut + "/_EM_19_XYZ_/transfer?EMextraParam123=42")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/_EM_19_XYZ_/transfer"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/v2/api-docs
    */
    @Test @Timeout(60)
    public void test_14_getOnApi_docsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/v2/api-docs")
                .then()
                .statusCode(200);
    }
    
    
    /**
    * Calls:
    * (400) GET:/{contractAddress}/decimals
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_15_getOnDecimalsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/{contractAddress}/decimals'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/VQ3Ae3h%5CSTj1/decimals")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (400) GET:/{contractAddress}/symbol
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_16_getOnSymbolReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/{contractAddress}/symbol'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/008a1%5C/symbol")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (400) GET:/{contractAddress}/name
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_17_getOnNameReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/{contractAddress}/name'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v6pqWba9l%5C/name")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (400) POST:/{contractAddress}/transfer
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_18_postOnTransferReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/{contractAddress}/transfer'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"to\": \"r_ltibcB3igfAaS\", " + 
                    " \"value\": 875 " + 
                    " } ")
                .post(baseUrlOfSut + "/%5C/transfer")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * (404) GET:/{contractAddress}/totalSupply
    * Found 1 potential fault of type-code 101
    */
    @Test @Timeout(60)
    public void test_19_getOnTotalSupplyReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.unexpected No response body is expected but one was found.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/;/totalSupply")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(404))
                .body("'error'", containsString("Not Found"))
                .body("'message'", containsString("No message available"))
                .body("'path'", containsString("/;/totalSupply"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/{contractAddress}/balanceOf/{ownerAddress}
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test @Timeout(60)
    public void test_20_getOnBalanceOfShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. io/blk/erc20/generated/HumanStandardToken_83_<init>
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/{contractAddress}/balanceOf/{ownerAddress}'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/Yh9xM6cH9dF8/balanceOf/gWGgIdw3lQX7ho1?EMextraParam123=42")
                .then()
                .statusCode(500)// io/blk/erc20/generated/HumanStandardToken_83_<init>
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'message'", containsString("Unable to determine sync status of node"))
                .body("'path'", containsString("/Yh9xM6cH9dF8/balanceOf/gWGgIdw3lQX7ho1"));
    }


}
