/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-04T13:24:42.913447122+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 52 tests
 * <br>
*  Covered targets: 499
 * <br>
*  Used time: 1h 2m 33s
 * <br>
*  Needed budget for current results: 51%
 * <br>
*  
*/
public class EM_quartz_manager_True_6_Test {

    
    private static final SutHandler controller = new em.external.quartz.manager.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "quartz-manager-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exec/quartz-manager__wbEnabledFlakiness__10370__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_11"));
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/triggers
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_0_getOnQuartz_managerTriggersWithQueryParamCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_20_XYZ_")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/triggers?EMextraParam123=42")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/triggers"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/triggers
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_1_getOnQuartz_managerTriggersWithQueryParamsCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/triggers?" + 
                    "password=_EM_88_XYZ_&" + 
                    "username=_EM_89_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/triggers"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_2_getOnQuartz_managerSchedulerReturnsObject() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("example"))
                .body("'instanceId'", containsString("NON_CLUSTERED"))
                .body("'status'", containsString("STOPPED"))
                .body("'triggerKeys'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_3_getOnJobsReturnsEmptyList() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/jobs?username=_EM_448_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_4_getOnJobsReturnsEmptyList() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/jobs?access_token=_EM_402_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_5_getOnSchedulerReturnsObject() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_32_XYZ_")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler?EMextraParam123=42")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("example"))
                .body("'instanceId'", containsString("NON_CLUSTERED"))
                .body("'status'", containsString("STOPPED"))
                .body("'triggerKeys'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_6_getOnSchedulerReturnsObject() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler?password=_EM_77_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("example"))
                .body("'instanceId'", containsString("NON_CLUSTERED"))
                .body("'status'", containsString("STOPPED"))
                .body("'triggerKeys'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_7_getOnQuartz_managerSchedulerWithQueryParamsReturnsObject() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler?" + 
                    "password=_EM_387_XYZ_&" + 
                    "username=_EM_388_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("example"))
                .body("'instanceId'", containsString("NON_CLUSTERED"))
                .body("'status'", containsString("STOPPED"))
                .body("'triggerKeys'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_8_getOnQuartz_managerJobsWithQueryParamsReturnsEmptyList() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/jobs?" + 
                    "password=er&" + 
                    "username=wZyOwA0uTOy")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_9_getOnApi_docsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/v3/api-docs")
                .then()
                .statusCode(200);
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/triggers
    */
    @Test @Timeout(60)
    public void test_10_getOnTriggersReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/triggers")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_11_getOnSchedulerReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler?access_token=_EM_803_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_12_getOnSchedulerReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_7_XYZ_")
                .get(baseUrlOfSut + "/quartz-manager/scheduler?EMextraParam123=_EM_6_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_13_getOnJobsReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/jobs?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_14_getOnQuartz_managerSimple_triggCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_16_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/_EM_16_XYZ_"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/run
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_15_getOnSchedulerRunCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/run"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/resume
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_16_getOnResumeCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?EMextraParam123=_EM_19_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/resume"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/run
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_17_getOnRunCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run?" + 
                    "EMextraParam123=42&" + 
                    "password=_EM_45_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/run"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/run
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_18_getOnRunCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run?" + 
                    "EMextraParam123=_EM_28_XYZ_&" + 
                    "password=b&" + 
                    "username=_EM_48_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/run"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_19_getOnQuartz_managerSimple_triggWithQueryParamsCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_511_XYZ_?" + 
                    "password=PZPeYEpTX_Z2GFW&" + 
                    "username=EearaOeb")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/_EM_511_XYZ_"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/resume
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_20_getOnResumeCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?password=_EM_96_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/resume"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/resume
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_21_getOnResumeCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?username=8E7ujYiCPUrb_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/resume"));
    }
    
    
    /**
    * Calls:
    * (500) PUT:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_22_putOnSimple_triggCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/security/helpers/impl/AuthenticationSuccessHandler_28_onAuthenticationSuccess
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .contentType("application/json")
                .body(" {} ")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/qLH5GUdY;0iBrc?" + 
                    "password=ambjbPnElp&" + 
                    "username=YwJY17Y")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/security/helpers/impl/AuthenticationSuccessHandler_28_onAuthenticationSuccess
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/qLH5GUdY;0iBrc"));
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_23_getOnStopReturns204() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_24_getOnPauseReturns204() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_25_getOnStopReturns204() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_26_getOnPauseReturns204() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_27_getOnSchedulerPauseWithQueryParamsReturns204() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause?" + 
                    "password=ZsfoLfCmShYh&" + 
                    "username=cYKFxo4pA")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_28_getOnSchedulerStopWithQueryParamsReturns204() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_81_XYZ_")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop?" + 
                    "password=_EM_82_XYZ_&" + 
                    "username=LaiiQMtWbq24")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (400) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_29_postOnSimple_triggReturns400() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/et2b?" + 
                    "EMextraParam123=_EM_182_XYZ_&" + 
                    "password=hlP8Y442c5afBu&" + 
                    "username=Nex")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/et2b"));
    }
    
    
    /**
    * Calls:
    * (400) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_30_putOnSimple_triggReturns400() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .contentType("application/json")
                .body(" {} ")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_501_XYZ_?" + 
                    "password=_EM_502_XYZ_&" + 
                    "username=YwJY17Y")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/_EM_501_XYZ_"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_31_getOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/Yh9xM6cH9dF8?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_32_getOnPauseReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause?access_token=GOV4GtVF5RLaOw")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_33_getOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/0fugB63PMgMz2ZLC?access_token=6C")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_34_getOnSchedulerStopWithQueryParamReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_1_XYZ_")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop?access_token=oZJuEW")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_35_getOnSchedulerStopReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_1_XYZ_")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/run
    */
    @Test @Timeout(60)
    public void test_36_getOnSchedulerRunWithQueryParamEmptyAccess_tokenReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run?access_token=")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/run
    */
    @Test @Timeout(60)
    public void test_37_getOnSchedulerRunWithQueryParamReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/resume
    */
    @Test @Timeout(60)
    public void test_38_getOnResumeReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_2_XYZ_")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?access_token=QvVytAF2ohVgPXokH")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/resume
    */
    @Test @Timeout(60)
    public void test_39_getOnResumeReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_2_XYZ_")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_40_getOnPauseReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause?EMextraParam123=_EM_3_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_41_postOnQuartz_managerSimple_triggWithQueryParamReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/0fugB63PMgMz2ZLC?access_token=cqID4jGFxCW")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_42_postOnQuartz_managerSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/y7x63grVTn")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/auth/login
    */
    @Test @Timeout(60)
    public void test_43_postOnAuthLoginReturns401() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_23_XYZ_")
                .header("Authorization", auth_USER_1) // USER_1
                .contentType("application/x-www-form-urlencoded")
                .body("username=bYKRyq3uefgfYX&password=1sRg")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401))
                .body("'error'", containsString("Unauthorized"))
                .body("'path'", containsString("/quartz-manager/auth/login"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/auth/login
    */
    @Test @Timeout(60)
    public void test_44_postOnLoginReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_13_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/quartz-manager/auth/login?EMextraParam123=_EM_12_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401))
                .body("'error'", containsString("Unauthorized"))
                .body("'path'", containsString("/quartz-manager/auth/login"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/auth/login
    */
    @Test @Timeout(60)
    public void test_45_postOnLoginReturns401() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_37_XYZ_")
                .header("Authorization", auth_USER_2) // USER_2
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/quartz-manager/auth/login?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401))
                .body("'error'", containsString("Unauthorized"))
                .body("'path'", containsString("/quartz-manager/auth/login"));
    }
    
    
    /**
    * Calls:
    * (401) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_46_putOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/0fVNoKR9Mr?access_token=fSM")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_47_putOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/0fNNoKR9Mr?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (415) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_48_postOnQuartz_managerSimple_triggWithQueryParamReturns415() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/09GwQrI5nFcAjs?EMextraParam123=42")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/09GwQrI5nFcAjs"));
    }
    
    
    /**
    * Calls:
    * (415) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_49_postOnQuartz_managerSimple_triggReturns415() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_1) // USER_1
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/ojDrR")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/ojDrR"));
    }
    
    
    /**
    * Calls:
    * (415) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_50_putOnQuartz_managerSimple_triggWithQueryParamsReturns415() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/67IPRle7X_gAF?" + 
                    "EMextraParam123=42&" + 
                    "username=rx")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/67IPRle7X_gAF"));
    }
    
    
    /**
    * Calls:
    * (415) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_51_putOnQuartz_managerSimple_triggReturns415() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_135_XYZ_")
                .header("Authorization", auth_USER_2) // USER_2
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_134_XYZ_")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/_EM_134_XYZ_"));
    }


}
