/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-06-08T17:43:01.158238177+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 45 tests
 * <br>
*  Covered targets: 500
 * <br>
*  Used time: 0h 21m 0s
 * <br>
*  Needed budget for current results: 55%
 * <br>
*  
*/
public class EM_quartz_manager_True_25_false_false_SPECIFIED_false_0_Test {

    
    private static final SutHandler controller = new em.external.quartz.manager.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "quartz-manager-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exp/exec/quartz-manager__wbMultiGiven__10370__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_11"));
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/triggers
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_0_getOnQuartz_managerTriggersCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_18_XYZ_")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/triggers")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/triggers"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/triggers
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_1_getOnQuartz_managerTriggersWithQueryParamsCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_57_XYZ_")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/triggers?" + 
                    "password=_EM_59_XYZ_&" + 
                    "username=r94")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/TriggerService_28_fetchTriggers
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/triggers"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_2_getOnQuartz_managerSchedulerWithQueryParamReturnsObject() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler?EMextraParam123=_EM_19_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("example"))
                .body("'instanceId'", containsString("NON_CLUSTERED"))
                .body("'status'", containsString("STOPPED"))
                .body("'triggerKeys'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_3_getOnQuartz_managerJobsReturnsEmptyList() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_21_XYZ_")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/jobs")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_4_getOnQuartz_managerJobsWithQueryParamsReturnsEmptyList() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/jobs?" + 
                    "password=8MYSQ6ppZi3&" + 
                    "username=UNL_7GJ")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_5_getOnQuartz_managerSchedulerWithQueryParamsReturnsObject() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler?" + 
                    "password=9&" + 
                    "username=nbon")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("example"))
                .body("'instanceId'", containsString("NON_CLUSTERED"))
                .body("'status'", containsString("STOPPED"))
                .body("'triggerKeys'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_6_getOnQuartz_managerJobsWithQueryParamReturnsEmptyList() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/jobs?access_token=_EM_256_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/v3/api-docs
    */
    @Test @Timeout(60)
    public void test_7_getOnApi_docsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/v3/api-docs")
                .then()
                .statusCode(200);
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/triggers
    */
    @Test @Timeout(60)
    public void test_8_getOnTriggersReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/quartz-manager/triggers")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_9_getOnQuartz_managerSchedulerReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/jobs
    */
    @Test @Timeout(60)
    public void test_10_getOnJobsReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/jobs?EMextraParam123=42")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler
    */
    @Test @Timeout(60)
    public void test_11_getOnQuartz_managerSchedulerWithQueryParamReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler?access_token=Pe")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_12_getOnSimple_triggCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_28_XYZ_?EMextraParam123=42")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/_EM_28_XYZ_"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/run
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_13_getOnSchedulerRunWithQueryParamCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run?EMextraParam123=42")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/run"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/run
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_14_getOnSchedulerRunCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/run"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/resume
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_15_getOnSchedulerResumeWithQueryParamCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?EMextraParam123=_EM_16_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/resume"));
    }
    
    
    /**
    * Calls:
    * 1 - (415) POST:/quartz-manager/simple-triggers/{name}
    * 2 - (500) GET:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_16_getOnQuartz_managerSimple_triggWithQueryParamsCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/RNZRmxtgPWE5KA")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/RNZRmxtgPWE5KA"));
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_43_XYZ_")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/RNZRmxtgPWE5KA?" + 
                    "EMextraParam123=_EM_42_XYZ_&" + 
                    "password=_EM_44_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/RNZRmxtgPWE5KA"));
    }
    
    
    /**
    * Calls:
    * 1 - (400) POST:/quartz-manager/simple-triggers/{name}
    * 2 - (500) GET:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_17_getOnQuartz_managerSimple_triggCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/JsanRsKcvZKKaM?" + 
                    "password=zpYvCX0cn&" + 
                    "username=pn")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/JsanRsKcvZKKaM"));
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/JsanRsKcvZKKaM")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/JsanRsKcvZKKaM"));
    }
    
    
    /**
    * Calls:
    * 1 - (400) PUT:/quartz-manager/simple-triggers/{name}
    * 2 - (500) GET:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_18_getOnSimple_triggCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_1) // USER_1
                .contentType("application/json")
                .body(" {} ")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/xpO5vW?" + 
                    "EMextraParam123=42&" + 
                    "password=T5skgAb&" + 
                    "username=H4s")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/xpO5vW"));
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
        given().accept("application/json")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/xpO5vW?EMextraParam123=42")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/xpO5vW"));
    }
    
    
    /**
    * Calls:
    * 1 - (415) POST:/quartz-manager/simple-triggers/{name}
    * 2 - (500) GET:/quartz-manager/simple-triggers/{name}
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_19_getOnSimple_triggCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/y5znDpey3F7O?EMextraParam123=_EM_48_XYZ_")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/y5znDpey3F7O"));
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
        given().accept("application/json")
                .header("x-EMextraHeader123", "_EM_49_XYZ_")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/y5znDpey3F7O?username=_EM_51_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/AbstractSchedulerService_18_getTriggerByName
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/y5znDpey3F7O"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/resume
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_20_getOnResumeCauses500_internalServerError() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?" + 
                    "password=TmH3W&" + 
                    "access_token=5cZr")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/resume"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/resume
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_21_getOnResumeCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume?" + 
                    "password=KjM68pjnWukcs3a&" + 
                    "username=9tENQvR")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/resume"));
    }
    
    
    /**
    * Calls:
    * (500) GET:/quartz-manager/scheduler/run
    * Found 1 potential fault of type-code 100
    */
    @Test @Timeout(60)
    public void test_22_getOnSchedulerRunWithQueryParamsCauses500_internalServerError() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        // Fault100. HTTP Status 500. it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run?" + 
                    "password=dQ7qdf&" + 
                    "username=_EM_145_XYZ_")
                .then()
                .statusCode(500)// it/fabioformosa/quartzmanager/api/services/SchedulerService_25_start
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(500))
                .body("'error'", containsString("Internal Server Error"))
                .body("'path'", containsString("/quartz-manager/scheduler/run"));
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_23_getOnSchedulerStopWithQueryParamReturns204() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_15_XYZ_")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop?EMextraParam123=_EM_14_XYZ_")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_24_getOnSchedulerPauseReturns204() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_17_XYZ_")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_25_getOnPauseReturns204() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause?password=LhX")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_26_getOnSchedulerStopWithQueryParamsReturns204() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop?" + 
                    "EMextraParam123=dIBEYBB&" + 
                    "password=_EM_120_XYZ_&" + 
                    "username=_EM_121_XYZ_")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (204) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_27_getOnPauseReturns204() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause?username=pMpXpt")
                .then()
                .statusCode(204)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (400) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_28_putOnSimple_triggReturns400() throws Exception {
        
        final String token_USER_2 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo2&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_2 = "Bearer " + token_USER_2;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_2) // USER_2
                .contentType("application/json")
                .body(" {} ")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/3cwDufITVq66?" + 
                    "password=42&" + 
                    "username=3CGp2Z8K55JSd")
                .then()
                .statusCode(400)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(400))
                .body("'error'", containsString("Bad Request"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/3cwDufITVq66"));
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_29_getOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_1_XYZ_")
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/31SVHZ51PHVA?EMextraParam123=_EM_0_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_30_getOnStopReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop?EMextraParam123=_EM_2_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/run
    */
    @Test @Timeout(60)
    public void test_31_getOnRunReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/run?access_token=WKk")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/resume
    */
    @Test @Timeout(60)
    public void test_32_getOnResumeReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/resume")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/pause
    */
    @Test @Timeout(60)
    public void test_33_getOnPauseReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/pause")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) GET:/quartz-manager/scheduler/stop
    */
    @Test @Timeout(60)
    public void test_34_getOnStopReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/quartz-manager/scheduler/stop?access_token=y3N_afV7m2ls1fHTs")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_35_postOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/oVjBpVzeVXgVUZi6?EMextraParam123=_EM_5_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/auth/login
    */
    @Test @Timeout(60)
    public void test_36_postOnLoginReturns401() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .contentType("application/x-www-form-urlencoded")
                .body("")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(401))
                .body("'error'", containsString("Unauthorized"))
                .body("'path'", containsString("/quartz-manager/auth/login"));
    }
    
    
    /**
    * Calls:
    * (401) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_37_postOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/oVjBpVzeVXgVUZi6?access_token=_EM_299_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (401) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_38_putOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_9_XYZ_?EMextraParam123=_EM_10_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * 1 - (401) POST:/quartz-manager/simple-triggers/{name}
    * 2 - (401) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_39_putOnSimple_triggReturns401() throws Exception {
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/fIV_e?access_token=_EM_308_XYZ_")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/fIV_e?access_token=fK_O")
                .then()
                .statusCode(401)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) GET:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_40_getOnSimple_triggReturns404() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .get(baseUrlOfSut + "/quartz-manager/simple-triggers/bHzzAnMjbOFRi")
                .then()
                // Flaky Status Code: 404 vs. 500
                // .statusCode(404)
                .assertThat()
                .contentType("application/json")
                // Flaky mismatched size of fields for Object : 2 vs. 4
                // Flaky mismatched field name: 'errorCode' vs. NONE
                ; // Flaky mismatched field name: 'errorMessage' vs. NONE
    }
    
    
    /**
    * Calls:
    * (415) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_41_postOnSimple_triggReturns415() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/HB0ITb?EMextraParam123=42")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/HB0ITb"));
    }
    
    
    /**
    * Calls:
    * (415) POST:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_42_postOnSimple_triggReturns415() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .post(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_25_XYZ_?EMextraParam123=42")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/_EM_25_XYZ_"));
    }
    
    
    /**
    * Calls:
    * (415) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_43_putOnQuartz_managerSimple_triggWithQueryParamReturns415() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/FmkvrnH?username=TinXPK9E")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/FmkvrnH"));
    }
    
    
    /**
    * Calls:
    * (415) PUT:/quartz-manager/simple-triggers/{name}
    */
    @Test @Timeout(60)
    public void test_44_putOnQuartz_managerSimple_triggReturns415() throws Exception {
        
        final String token_USER_1 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("username=foo&password=bar")
                .post(baseUrlOfSut + "/quartz-manager/auth/login")
                .then().extract().response().path("accessToken");
                
        final String auth_USER_1 = "Bearer " + token_USER_1;
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_USER_1) // USER_1
                .put(baseUrlOfSut + "/quartz-manager/simple-triggers/_EM_26_XYZ_")
                .then()
                .statusCode(415)
                .assertThat()
                .contentType("application/json")
                .body("'status'", numberMatches(415))
                .body("'error'", containsString("Unsupported Media Type"))
                .body("'path'", containsString("/quartz-manager/simple-triggers/_EM_26_XYZ_"));
    }


}
