/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-04T21:20:50.211672292+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 21 tests
 * <br>
*  Covered targets: 764
 * <br>
*  Used time: 1h 2m 47s
 * <br>
*  Needed budget for current results: 75%
 * <br>
*  
*/
public class EM_spring_batch_rest_False_6_Test {

    
    private static final SutHandler controller = new em.external.spring.batch.rest.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "spring-batch-rest-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exec/spring-batch-rest__wbEnabledFlakiness__10560__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_8"));
    private static String baseUrlOfSut;
    
    
    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @Before
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (500) GET:/jobExecutions
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_0_getOnJobExecutionsWithQueryParamsNegativeLimitPerJobShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. com/github/chrisgleissner/springbatchrest/api/core/jobexecution/provider/CachedJobExecutionProvider$JobExecutions_73_getJobExecutions
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/jobExecutions'.
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/jobExecutions?" + 
                    "jobName=personJob&" + 
                    "exitCode=5AYAuEc_&" + 
                    "limitPerJob=-67109750")
                .then()
                .statusCode(500)// com/github/chrisgleissner/springbatchrest/api/core/jobexecution/provider/CachedJobExecutionProvider$JobExecutions_73_getJobExecutions
                .assertThat()
                .contentType("application/hal+json")
                .body("'status'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'message'", nullValue())
                .body("'exception'", containsString("NullPointerException"))
                .body("'detail'", containsString(""));
    }
    
    
    /**
    * Calls:
    * (500) GET:/jobExecutions
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_1_getOnJobExecutionsWithQueryParamsEmptyJobNameShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. com/github/chrisgleissner/springbatchrest/api/core/jobexecution/provider/CachedJobExecutionProvider$JobExecutions_73_getJobExecutions
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/jobExecutions'.
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/jobExecutions?" + 
                    "jobName=&" + 
                    "exitCode=_EM_271_XYZ_")
                .then()
                .statusCode(500)// com/github/chrisgleissner/springbatchrest/api/core/jobexecution/provider/CachedJobExecutionProvider$JobExecutions_73_getJobExecutions
                .assertThat()
                .contentType("application/hal+json")
                .body("'status'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'message'", nullValue())
                .body("'exception'", containsString("NullPointerException"))
                .body("'detail'", containsString(""));
    }
    
    
    /**
    * Calls:
    * (null) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_2_getOnJobExecutionsReturnsNull() throws Exception {
        
        try{
            given().accept("*/*")
                    .header("x-EMextraHeader123", "")
                    .get(baseUrlOfSut + "/jobExecutions?" + 
                        "jobName=&" + 
                        "exitCode=COMPLETED&" + 
                        "limitPerJob=788");
        } catch(Exception e){
        }
    }
    
    
    /**
    * Calls:
    * (null) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_3_getOnJobExecutionsReturnsNull() throws Exception {
        
        try{
            given().accept("*/*")
                    .header("x-EMextraHeader123", "")
                    .get(baseUrlOfSut + "/jobExecutions?" + 
                        "jobName=&" + 
                        "exitCode=_EM_346_XYZ_&" + 
                        "limitPerJob=8928");
        } catch(Exception e){
        }
    }
    
    
    /**
    * Calls:
    * (500) GET:/jobExecutions
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_4_getOnJobExecutionsWithQueryParamNegativeLimitPerJobShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. com/github/chrisgleissner/springbatchrest/api/core/jobexecution/provider/CachedJobExecutionProvider_55_lambda$getJobExecutions$2
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/jobExecutions'.
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/jobExecutions?limitPerJob=-67109750")
                .then()
                .statusCode(500)// com/github/chrisgleissner/springbatchrest/api/core/jobexecution/provider/CachedJobExecutionProvider_55_lambda$getJobExecutions$2
                .assertThat()
                .contentType("application/hal+json")
                .body("'status'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'message'", containsString("-67109750"))
                .body("'exception'", containsString("IllegalArgumentException"))
                .body("'detail'", containsString(""));
    }
    
    
    /**
    * Calls:
    * (500) POST:/jobExecutions
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_5_postOnJobExecutionsShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. com/github/chrisgleissner/springbatchrest/util/core/AdHocStarter_95_start
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/jobExecutions'.
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "_EM_180_XYZ_")
                .contentType("application/json")
                .body(" {} ")
                .post(baseUrlOfSut + "/jobExecutions")
                .then()
                .statusCode(500)// com/github/chrisgleissner/springbatchrest/util/core/AdHocStarter_95_start
                .assertThat()
                .contentType("application/hal+json")
                .body("'status'", containsString("500 INTERNAL_SERVER_ERROR"))
                .body("'message'", containsString("Failed to start job 'null' with JobConfig(name=null, properties={}, asynchronous=false). Reason: null"))
                .body("'exception'", containsString("RuntimeException"))
                .body("'detail'", nullValue());
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobs
    */
    @Test(timeout = 60000)
    public void test_6_getOnJobsReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "_EM_10_XYZ_")
                .get(baseUrlOfSut + "/jobs?EMextraParam123=42")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'_embedded'.'jobResourceList'.size()", equalTo(1))
                .body("'_embedded'.'jobResourceList'[0].'job'.'name'", containsString("personJob"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_7_getOnJobExecutionsReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/jobExecutions?" + 
                    "exitCode=COMPLETED&" + 
                    "limitPerJob=12")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'_embedded'.'jobExecutionResourceList'.size()", equalTo(12))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'jobId'", numberMatches(597))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'jobName'", containsString("personJob"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'startTime'", containsString("2026-03-04T21:20:21.172"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'endTime'", containsString("2026-03-04T21:20:21.174"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'exitDescription'", containsString(""))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'exceptions'.size()", equalTo(0))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'jobId'", numberMatches(596))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'jobName'", containsString("personJob"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'startTime'", containsString("2026-03-04T21:20:19.648"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'endTime'", containsString("2026-03-04T21:20:19.651"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'exitDescription'", containsString(""))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'exceptions'.size()", equalTo(0))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'jobId'", numberMatches(595))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'jobName'", containsString("personJob"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'startTime'", containsString("2026-03-04T21:20:14.392"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'endTime'", containsString("2026-03-04T21:20:14.396"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'exitDescription'", containsString(""))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'exceptions'.size()", equalTo(0))
                ; // Skipping assertions on the remaining 9 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_8_getOnJobExecutionsReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/jobExecutions?" + 
                    "jobName=personJob&" + 
                    "exitCode=5AYAuEc_&" + 
                    "limitPerJob=138")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json");
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_9_getOnJobExecutionsReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/jobExecutions?" + 
                    "jobName=_EM_11_XYZ_&" + 
                    "limitPerJob=450&" + 
                    "EMextraParam123=42")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json");
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_10_getOnJobExecutionsWithQueryParamReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/jobExecutions?EMextraParam123=42")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'_embedded'.'jobExecutionResourceList'.size()", equalTo(3))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'jobId'", numberMatches(592))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'jobName'", containsString("personJob"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'startTime'", containsString("2026-03-04T21:18:22.599"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'endTime'", containsString("2026-03-04T21:18:22.601"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'exitDescription'", containsString(""))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[0].'jobExecution'.'exceptions'.size()", equalTo(0))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'jobId'", numberMatches(591))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'jobName'", containsString("personJob"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'startTime'", containsString("2026-03-04T21:18:20.095"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'endTime'", containsString("2026-03-04T21:18:20.098"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'exitDescription'", containsString(""))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[1].'jobExecution'.'exceptions'.size()", equalTo(0))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'jobId'", numberMatches(590))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'jobName'", containsString("personJob"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'startTime'", containsString("2026-03-04T21:18:07.321"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'endTime'", containsString("2026-03-04T21:18:07.324"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'exitDescription'", containsString(""))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'_embedded'.'jobExecutionResourceList'[2].'jobExecution'.'exceptions'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_11_getOnJobExecutionsWithQueryParamsNegativeLimitPerJobReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "_EM_323_XYZ_")
                .get(baseUrlOfSut + "/jobExecutions?" + 
                    "jobName=_EM_359_XYZ_&" + 
                    "limitPerJob=-4194056")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json");
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobExecutions
    */
    @Test(timeout = 60000)
    public void test_12_getOnJobExecutionsReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/jobExecutions?" + 
                    "jobName=n&" + 
                    "exitCode=COMPLETED&" + 
                    "limitPerJob=3")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json");
    }
    
    
    /**
    * Calls:
    * (200) POST:/jobExecutions
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_13_postOnJobExecutionsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.type [Path '/jobExecution/endTime'] Instance type (null) does not match any allowed primitive type (allowed: ["string"])
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"personJob\", " + 
                    " \"properties\": { " + 
                    " \"pISlEnYQqhq\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"P\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"K\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"nvQH8Qzi\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " } " + 
                    " }, " + 
                    " \"asynchronous\": true " + 
                    " } ")
                .post(baseUrlOfSut + "/jobExecutions")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'jobExecution'.'jobId'", numberMatches(591))
                .body("'jobExecution'.'jobName'", containsString("personJob"))
                .body("'jobExecution'.'startTime'", nullValue())
                .body("'jobExecution'.'endTime'", nullValue())
                .body("'jobExecution'.'exitCode'", containsString("UNKNOWN"))
                .body("'jobExecution'.'exitDescription'", containsString(""))
                .body("'jobExecution'.'status'", containsString("STARTING"))
                .body("'jobExecution'.'exceptions'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) POST:/jobExecutions
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_14_postOnJobExecutionsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.format.date-time [Path '/jobExecution/endTime'] String "2026-03-04T21:18:59.108" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"personJob\", " + 
                    " \"properties\": { " + 
                    " \"pISlEnYQqhq\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"P\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"K\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"nvQH8Qz\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " } " + 
                    " }, " + 
                    " \"asynchronous\": false " + 
                    " } ")
                .post(baseUrlOfSut + "/jobExecutions")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'jobExecution'.'jobId'", numberMatches(593))
                .body("'jobExecution'.'jobName'", containsString("personJob"))
                .body("'jobExecution'.'startTime'", containsString("2026-03-04T21:18:59.106"))
                .body("'jobExecution'.'endTime'", containsString("2026-03-04T21:18:59.108"))
                .body("'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'jobExecution'.'exitDescription'", containsString(""))
                .body("'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'jobExecution'.'exceptions'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (400) POST:/jobExecutions
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_15_postOnJobExecutionsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/jobExecutions'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .post(baseUrlOfSut + "/jobExecutions?EMextraParam123=_EM_13_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (404) POST:/jobExecutions
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_16_postOnJobExecutionsReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/jobExecutions'.
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .contentType("application/json")
                .body(" { " + 
                    " \"name\": \"RmMWI3Ji3DXvodWk\", " + 
                    " \"properties\": { " + 
                    " \"2qqFRfCDj\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"_EM_233_XYZ_\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"_EM_234_XYZ_\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " }, " + 
                    " \"_EM_235_XYZ_\": { " + 
                    " \"EM_tainted_map\": \"_EM_0_XYZ_\" " + 
                    " } " + 
                    " } " + 
                    " } ")
                .post(baseUrlOfSut + "/jobExecutions?EMextraParam123=42")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/hal+json")
                .body("'status'", containsString("404 NOT_FOUND"))
                .body("'message'", containsString("No job configuration with the name [RmMWI3Ji3DXvodWk] was registered"))
                .body("'exception'", containsString("NoSuchJobException"))
                .body("'detail'", containsString("Failed to start job 'RmMWI3Ji3DXvodWk' with JobConfig(name=RmMWI3Ji3DXvodWk, properties={2qqFRfCDj={EM_tainted_map=_EM_0_XYZ_}, _EM_233_XYZ_={EM_tainted_map=_EM_0_XYZ_}, _EM_234_XYZ_={EM_tainted_map=_EM_0_XYZ_}, _EM_235_XYZ_={EM_tainted_map=_EM_0_XYZ_}}, asynchronous=false). Reason: No job configuration with the name [RmMWI3Ji3DXvodWk] was registered"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobs/{jobName}
    */
    @Test(timeout = 60000)
    public void test_17_getOnJobReturnsObject() throws Exception {
        
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/jobs/Yh9xM6cH9dF8?EMextraParam123=_EM_8_XYZ_")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'job'.'name'", containsString("Yh9xM6cH9dF8"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/jobExecutions/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_18_getOnJobExecutReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.body.schema.format.date-time [Path '/jobExecution/endTime'] String "2026-03-04T20:22:10.316" is invalid against requested date format(s) [yyyy-MM-dd'T'HH:mm:ssZ, yyyy-MM-dd'T'HH:mm:ss.[0-9]{1,12}Z]
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/jobExecutions/7")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/hal+json")
                .body("'jobExecution'.'jobId'", numberMatches(7))
                .body("'jobExecution'.'jobName'", containsString("personJob"))
                .body("'jobExecution'.'startTime'", containsString("2026-03-04T20:22:10.311"))
                .body("'jobExecution'.'endTime'", containsString("2026-03-04T20:22:10.316"))
                .body("'jobExecution'.'exitCode'", containsString("COMPLETED"))
                .body("'jobExecution'.'exitDescription'", containsString(""))
                .body("'jobExecution'.'status'", containsString("COMPLETED"))
                .body("'jobExecution'.'exceptions'.size()", equalTo(0));
    }
    
    
    /**
    * Calls:
    * (200) GET:/v3/api-docs
    */
    @Test(timeout = 60000)
    public void test_19_getOnApi_docsReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/v3/api-docs")
                .then()
                .statusCode(200);
    }
    
    
    /**
    * Calls:
    * (404) GET:/jobExecutions/{id}
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_20_getOnJobExecutWithQueryParamReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 404 not defined for path '/jobExecutions/{id}'.
        given().accept("application/hal+json")
                .header("x-EMextraHeader123", "42")
                .get(baseUrlOfSut + "/jobExecutions/-1237497730883472507?EMextraParam123=_EM_9_XYZ_")
                .then()
                .statusCode(404)
                .assertThat()
                .contentType("application/hal+json")
                .body("'status'", containsString("404 NOT_FOUND"))
                .body("'message'", containsString("Could not find job execution with ID -1237497730883472507"))
                .body("'exception'", containsString("NoSuchJobExecutionException"))
                .body("'detail'", containsString(""));
    }


}
