/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-04T20:10:13.167774634+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 30 tests
 * <br>
*  Covered targets: 1975
 * <br>
*  Used time: 1h 2m 5s
 * <br>
*  Needed budget for current results: 92%
 * <br>
*  
*/
public class EM_languagetool_False_6_Test {

    
    private static final SutHandler controller = new em.external.org.languagetool.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "languagetool-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exec/languagetool__wbEnabledFlakiness__10220__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_8"));
    private static String baseUrlOfSut;
    
    
    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @Before
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_0_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_173_getMode
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=0ob&language=n7ad8u4v9FXZX&altLanguages=_EM_4179_XYZ_&motherTongue=_EM_4193_XYZ_&preferredVariants=RTzYXLjMbxbp1&enabledRules=_EM_4180_XYZ_&enabledCategories=dg&disabledCategories=h50G&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=1HYl%40&" + 
                    "instanceId=_EM_4191_XYZ_&" + 
                    "inputLogging=_EM_354_XYZ_&" + 
                    "apiKey=A2&" + 
                    "tokenV2=PiGC8ZJMRUSnNTAT&" + 
                    "level=picky&" + 
                    "v=Mv9imS&" + 
                    "useragent=_EM_4194_XYZ_&" + 
                    "username=r")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_173_getMode
                .assertThat()
                .body(containsString("Error: Internal Error: sqlSessionFactory not initialized - has the database been configured?"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_1_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_191_getLevel
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("data=EAW6z7_XTnLw&language=erEfyl2sow&altLanguages=2il&motherTongue=_EM_2712_XYZ_&preferredVariants=MrEKVe&enabledRules=5SqzoA6&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=_EM_2716_XYZ_&" + 
                    "tokenV2=%5Bz&" + 
                    "level=_EM_2717_XYZ_&" + 
                    "ruleValues=TXWI%5E&" + 
                    "useragent=_EM_2718_XYZ_&" + 
                    "noopLanguages=TGEymmrEkHCxL&" + 
                    "enabled=lES2ZNlv5M94XpF&" + 
                    "token=VzDAHA&" + 
                    "mode=2oLia8EWpq&" + 
                    "password=_EM_2719_XYZ_&" + 
                    "instanceId=_EM_2720_XYZ_&" + 
                    "preferredLanguages=qKE&" + 
                    "textSessionId=W14fT7SHN")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_191_getLevel
                .assertThat()
                .body(containsString("Error: Internal Error: Unrecognized token 'EAW6z7_XTnLw': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (String)\"EAW6z7_XTnLw\"; line: 1, column: 13]"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_2_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_191_getLevel
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=0ob&language=_EM_269_XYZ_&altLanguages=wY80xlvHpcr&motherTongue=_EM_271_XYZ_&preferredVariants=RTzYXLjMbxbp1&enabledRules=rlzEbkSB3o&enabledCategories=dfc&disabledCategories=h90G")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=1LYh%406&" + 
                    "instanceId=eBCnfP&" + 
                    "inputLogging=_EM_354_XYZ_&" + 
                    "apiKey=A2&" + 
                    "tokenV2=_EM_355_XYZ_&" + 
                    "level=Rn&" + 
                    "v=q&" + 
                    "useragent=hgUDZMnEgy&" + 
                    "username=n")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_191_getLevel
                .assertThat()
                .body(containsString("Error: Internal Error: sqlSessionFactory not initialized - has the database been configured?"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_3_postOnV2CheckWithQueryParamsEmptyInputLoggingAndEmptyRuleValuesShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/UserLimits_71_getLimitsFromToken
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=29IeBo7v_a4SXw&language=y&motherTongue=_EM_2508_XYZ_&preferredVariants=d5Hn_yqRUr2_1s&disabledCategories=Kq4E52Y")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=_EM_2510_XYZ_&" + 
                    "inputLogging=&" + 
                    "ruleValues=&" + 
                    "useragent=yHdey5dj&" + 
                    "noopLanguages=KTonPjV6S9SbSEc3&" + 
                    "token=ti&" + 
                    "filterDictionaryMatches=knWi4gRhr&" + 
                    "textSessionId=_EM_2515_XYZ_")
                .then()
                .statusCode(500)// org/languagetool/server/UserLimits_71_getLimitsFromToken
                .assertThat()
                .body(containsString("Error: Internal Error: You specified a 'token' parameter but this server doesn't accept tokens"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_4_postOnV2CheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ApiV2_153_handleCheckRequest
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("data=m1G6CZnD_Z&language=bshm9Q8Yx2FMlWe&enabledCategories=_EM_79_XYZ_")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(500)// org/languagetool/server/ApiV2_153_handleCheckRequest
                .assertThat()
                .body(containsString("Error: Internal Error: Unrecognized token 'm1G6CZnD_Z': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (String)\"m1G6CZnD_Z\"; line: 1, column: 11]"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_5_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/DatabaseAccess_187_getUserId
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=E0vUvR6&language=VEFS4LT&altLanguages=wY80xlvHpbrA&motherTongue=SU1i&preferredVariants=&enabledRules=_EM_4139_XYZ_&disabledRules=_EM_4143_XYZ_&enabledCategories=bUc&disabledCategories=h50A&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=all&" + 
                    "instanceId=XnhqRYulS8U6NsuPTT&" + 
                    "inputLogging=UMj956DD8i&" + 
                    "apiKey=Kkh8&" + 
                    "tokenV2=aRH7V34O&" + 
                    "level=default&" + 
                    "v=hXD8sCUf88&" + 
                    "useragent=aNgG&" + 
                    "username=Daswupo")
                .then()
                .statusCode(500)// org/languagetool/server/DatabaseAccess_187_getUserId
                .assertThat()
                .body(containsString("Error: Internal Error: sqlSessionFactory not initialized - has the database been configured?"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_6_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_191_getLevel
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_4138_XYZ_&language=VEFS4LT&altLanguages=wY80xlvHpbr&motherTongue=Sc0h&preferredVariants=42&enabledRules=_EM_4139_XYZ_&disabledRules=GmFX3sW&enabledCategories=dfc&disabledCategories=h90%3F&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=textLevelOnly&" + 
                    "instanceId=hPk8&" + 
                    "inputLogging=%7DMj956DD8i0&" + 
                    "apiKey=UUh&" + 
                    "tokenV2=QAMF&" + 
                    "level=_EM_4137_XYZ_&" + 
                    "v=hXD8sCSh88&" + 
                    "useragent=bPgDE&" + 
                    "username=_EM_4141_XYZ_")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_191_getLevel
                .assertThat()
                .body(containsString("Error: Internal Error: sqlSessionFactory not initialized - has the database been configured?"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/v2/languages
    */
    @Test(timeout = 60000)
    public void test_7_getOnLanguagesReturns44Elements() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/languages?EMextraParam123=42")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(44))
                .body("[0].'name'", containsString("Arabic"))
                .body("[0].'code'", containsString("ar"))
                .body("[0].'longCode'", containsString("ar"))
                .body("[1].'name'", containsString("Asturian"))
                .body("[1].'code'", containsString("ast"))
                .body("[1].'longCode'", containsString("ast-ES"))
                .body("[2].'name'", containsString("Belarusian"))
                .body("[2].'code'", containsString("be"))
                .body("[2].'longCode'", containsString("be-BY"))
                ; // Skipping assertions on the remaining 41 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (200) GET:/v2/swagger
    */
    @Test(timeout = 60000)
    public void test_8_getOnSwaggerReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/v2/swagger")
                .then()
                .statusCode(200);
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_9_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=3OPfkQcBGLhIw_hh&language=auto&altLanguages=mzElFR21GQs&disabledRules=_EM_2705_XYZ_&disabledCategories=0jSOmCPmxiijWSb")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'mzElFR21GQs' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_10_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_4_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("text=gWGgIdw3lQX7ho1&language=UF04mci&altLanguages=_EM_1_XYZ_&motherTongue=NOjinUZy0")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'UF04mci' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_11_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_2622_XYZ_&language=GA&altLanguages=_EM_2623_XYZ_&motherTongue=_EM_2539_XYZ_&enabledRules=_EM_2536_XYZ_&disabledRules=_EM_2265_XYZ_&enabledCategories=_EM_2540_XYZ_&disabledCategories=_EM_2541_XYZ_&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_2539_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_12_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=a&language=hSczwY&motherTongue=_EM_1150_XYZ_&enabledRules=M&disabledRules=_EM_1069_XYZ_&enabledCategories=vKbkJYWjN170SW0k&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=_EM_243_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'hSczwY' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_13_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_15_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("language=_EM_17_XYZ_&altLanguages=Dfyst9QyfO1WHqkj&preferredVariants=_EM_18_XYZ_&enabledRules=csXUVBEf9Dbtf3uy&enabledCategories=_EM_20_XYZ_")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Missing 'text' or 'data' parameter"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_14_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=8ooWPh9r0I&data=Eitv&language=UF04mci&altLanguages=_EM_1_XYZ_&motherTongue=UOjUnUUy0&preferredVariants=U6_7yzJojWpF4&enabledRules=xT7E8bGXLK&disabledRules=_EM_2_XYZ_&disabledCategories=yox8_A&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "EMextraParam123=42&" + 
                    "apiKey=_EM_227_XYZ_&" + 
                    "inputLogging=no&" + 
                    "tokenV2=b3Mlb4dFL0&" + 
                    "level=_EM_750_XYZ_&" + 
                    "ruleValues=TsH&" + 
                    "useragent=_EM_751_XYZ_&" + 
                    "noopLanguages=zA&" + 
                    "enabled=_EM_705_XYZ_&" + 
                    "token=tQWQBN4Ui&" + 
                    "mode=o6PSt8USp9W2X&" + 
                    "password=dCLLfX753Zv37o7t&" + 
                    "autodetect=_EM_232_XYZ_&" + 
                    "instanceId=eXGUyi_3EPu_vP&" + 
                    "filterDictionaryMatches=0MdQlUPjU&" + 
                    "v=IIlOTkK&" + 
                    "preferredLanguages=_EM_707_XYZ_&" + 
                    "textSessionId=5i&" + 
                    "disabled=_EM_752_XYZ_&" + 
                    "username=kZvqX5TxAow2OH")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Set only 'text' or 'data' parameter, not both"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_15_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_31_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("text=bpiu9yNw99cZI8T&language=_EM_38_XYZ_&motherTongue=_EM_39_XYZ_&preferredVariants=_EM_40_XYZ_&disabledRules=_EM_41_XYZ_&enabledCategories=_EM_42_XYZ_&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "EMextraParam123=42&" + 
                    "apiKey=oTFVAYBGU00P&" + 
                    "inputLogging=_EM_43_XYZ_&" + 
                    "tokenV2=_EM_44_XYZ_&" + 
                    "level=_EM_45_XYZ_&" + 
                    "useragent=_EM_47_XYZ_&" + 
                    "noopLanguages=aqZb2&" + 
                    "token=_EM_48_XYZ_&" + 
                    "password=_EM_50_XYZ_&" + 
                    "autodetect=_EM_51_XYZ_&" + 
                    "instanceId=_EM_52_XYZ_&" + 
                    "filterDictionaryMatches=_EM_53_XYZ_&" + 
                    "textSessionId=_EM_55_XYZ_&" + 
                    "disabled=_EM_56_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'disabled' but the parameter is now called 'disabledRules' in v2 of the API"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_16_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=gWGgIdw3lQX7ho1&language=UF04mci&altLanguages=_EM_1_XYZ_&motherTongue=NOjinUZy0")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "EMextraParam123=42&" + 
                    "apiKey=_EM_7_XYZ_&" + 
                    "inputLogging=NfKzZ5oW&" + 
                    "tokenV2=_EM_8_XYZ_&" + 
                    "level=3YXCjwOlPGyY12&" + 
                    "ruleValues=TsH&" + 
                    "useragent=Jmf47p%60&" + 
                    "noopLanguages=_EM_9_XYZ_&" + 
                    "enabled=w&" + 
                    "token=VMZ&" + 
                    "mode=_EM_10_XYZ_&" + 
                    "password=dCLLjX753Zv37o7t&" + 
                    "autodetect=_EM_11_XYZ_&" + 
                    "instanceId=_EM_12_XYZ_&" + 
                    "filterDictionaryMatches=_EM_13_XYZ_&" + 
                    "v=IIlOTkK&" + 
                    "preferredLanguages=Uxp4lY12nXNPyJs&" + 
                    "textSessionId=5i&" + 
                    "disabled=JuoMa0kaz&" + 
                    "username=_EM_14_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'enabled' but the parameter is now called 'enabledRules' in v2 of the API"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_17_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "aYmfCD")
                .contentType("application/x-www-form-urlencoded")
                .body("text=4QAMQr&language=RK0lat6bR9bRWh7c&motherTongue=DqygxBNNabVaQor&disabledRules=G&disabledCategories=sphbp6OxFOx")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=_EM_1583_XYZ_&" + 
                    "inputLogging=_EM_1584_XYZ_&" + 
                    "tokenV2=AE&" + 
                    "level=_EM_1585_XYZ_&" + 
                    "useragent=q454iLtnt0fxUri0&" + 
                    "mode=dlUZ_b&" + 
                    "password=ivppNXH&" + 
                    "filterDictionaryMatches=_EM_1587_XYZ_&" + 
                    "textSessionId=4QAMQr")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: apiKey was set, but username was not: _EM_1583_XYZ_"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_18_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=kysIOkeB&language=&altLanguages=qSEXKqDB5PFRI&preferredVariants=tkZvu&enabledRules=F2tAbnBB6_95C&disabledRules=qP0gbyLF&enabledCategories=kl3RBCIkuwU1b9JX&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=l9GECds5G&" + 
                    "instanceId=2n&" + 
                    "inputLogging=_EM_4319_XYZ_&" + 
                    "apiKey=QNeDoz&" + 
                    "tokenV2=_EM_4320_XYZ_&" + 
                    "level=PqTwClzcI90bNJy&" + 
                    "v=VCs4urj&" + 
                    "useragent=ALFVm9PmJP4nROu&" + 
                    "username=PMhc0qg")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Missing 'language' parameter, e.g. 'language=en-US' for American English or 'language=fr' for French"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_19_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=3OPfkQcBGLhIw_hh&language=auto&altLanguages=mzElFR21GQs&motherTongue=&enabledRules=z&disabledRules=_EM_2705_XYZ_&disabledCategories=0jSOmCPmxiijWSb&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: langCode cannot be empty or whitespace only"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_20_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=dc799v4SJNTs2&language=_EM_1868_XYZ_&enabledRules=SMYGxbWiK")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=6PSPv&" + 
                    "tokenV2=u9Uzw&" + 
                    "token=_EM_1876_XYZ_&" + 
                    "password=V7825Wj&" + 
                    "autodetect=Vsf1T9FzXj&" + 
                    "instanceId=YV1AoHbkmScabcnJ&" + 
                    "filterDictionaryMatches=_EM_1877_XYZ_&" + 
                    "v=_EM_1878_XYZ_&" + 
                    "textSessionId=_EM_1879_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'autodetect' but automatic language detection is now activated with 'language=auto' in v2 of the API"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_21_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_2793_XYZ_&language=auto&altLanguages=_EM_2794_XYZ_&motherTongue=dscpJ8B25oXj&preferredVariants=Ki808Hxt&enabledRules=hGKM&disabledRules=iebUqODK&enabledCategories=_EM_2795_XYZ_&disabledCategories=4eJt7vF&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Invalid format for 'preferredVariants', expected a dash as in 'en-GB': 'Ki808Hxt'"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_22_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/x-www-form-urlencoded")
                .body("text=SwmMVW0ZBn9i&language=vNwNbPWnDtRprl&motherTongue=y&preferredVariants=_EM_81_XYZ_&enabledRules=_EM_82_XYZ_&disabledRules=liw&disabledCategories=5C&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'preferredVariants' but you didn't specify 'language=auto'"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_23_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=&language=_EM_2262_XYZ_&motherTongue=Q74k&enabledRules=_EM_2264_XYZ_&disabledRules=_EM_2265_XYZ_&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_2262_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_24_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=3OPfkQcBGLhIw_hh&language=-x-&altLanguages=mzElFR21GQs&motherTongue=&enabledRules=z&disabledRules=Cn5tmem&enabledCategories=O&disabledCategories=0jSOmCPmxiijWSb&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '-x-' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_25_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_4_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("text=cWGgIdw3lQX7ho1&data=Eitv&language=UJ04mc&altLanguages=_EM_1_XYZ_&motherTongue=_EM_976_XYZ_&preferredVariants=U6_7yzJojWpF4&disabledRules=_EM_2_XYZ_&disabledCategories=_EM_3_XYZ_&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=yNeoctyerh8D&" + 
                    "inputLogging=_EM_977_XYZ_&" + 
                    "tokenV2=_EM_493_XYZ_&" + 
                    "level=_EM_978_XYZ_&" + 
                    "ruleValues=TtH&" + 
                    "useragent=_EM_979_XYZ_&" + 
                    "noopLanguages=_EM_495_XYZ_&" + 
                    "enabled=_EM_496_XYZ_&" + 
                    "token=O&" + 
                    "mode=allButTextLevelOnly&" + 
                    "password=dULLUU75UZU38mUt&" + 
                    "autodetect=ik&" + 
                    "instanceId=_EM_12_XYZ_&" + 
                    "filterDictionaryMatches=Ah4ir%3AXFiUUakT&" + 
                    "v=_EM_498_XYZ_&" + 
                    "preferredLanguages=_EM_980_XYZ_&" + 
                    "textSessionId=eexTKRe8wEWE&" + 
                    "disabled=JuoMa0kaz&" + 
                    "username=_EM_981_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Set only 'text' or 'data' parameter, not both"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_26_postOnV2CheckWithQueryParamsEmptyTokenV2ReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_1856_XYZ_&language=_EM_1267_XYZ_&motherTongue=_EM_1857_XYZ_&preferredVariants=So2&enabledRules=b&disabledRules=_EM_1147_XYZ_&enabledCategories=_EM_1858_XYZ_&disabledCategories=_EM_1859_XYZ_&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=_EM_1851_XYZ_&" + 
                    "inputLogging=_EM_1860_XYZ_&" + 
                    "tokenV2=&" + 
                    "level=default&" + 
                    "ruleValues=_EM_1861_XYZ_&" + 
                    "useragent=_EM_1862_XYZ_&" + 
                    "enabled=rd_kZ5cP8L&" + 
                    "token=Y&" + 
                    "mode=_EM_1863_XYZ_&" + 
                    "autodetect=8wva&" + 
                    "password=srp3pC1DJxFL9v&" + 
                    "filterDictionaryMatches=_EM_1864_XYZ_&" + 
                    "v=kBl&" + 
                    "textSessionId=_EM_1854_XYZ_&" + 
                    "disabled=PvXAVWSaKF0mfTTv&" + 
                    "multilingual=_EM_1855_XYZ_&" + 
                    "username=_EM_1865_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'enabled' but the parameter is now called 'enabledRules' in v2 of the API"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_27_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("data=&language=eNb&preferredVariants=Hiqxcp1c4&enabledRules=lc&disabledCategories=oQQd")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'data' key in JSON requires 'text' or 'annotation' key"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_28_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=O&language=_EM_712_XYZ_&altLanguages=EfV2DCLUQm7bUT&motherTongue=WFzeXZe&enabledRules=_EM_714_XYZ_&enabledCategories=Pz21IVA&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_712_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_29_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=3OPfkQcBGLhIw_hh&language=auto&altLanguages=mzElFR21GQs&enabledRules=z&disabledRules=_EM_2705_XYZ_&disabledCategories=0jSOmCPmxiijWSb&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'mzElFR21GQs' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }


}
