/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.AfterClass;
import  org.junit.BeforeClass;
import  org.junit.Before;
import  org.junit.Test;
import static org.junit.Assert.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-04T13:24:04.896366150+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 31 tests
 * <br>
*  Covered targets: 2129
 * <br>
*  Used time: 1h 2m 6s
 * <br>
*  Needed budget for current results: 89%
 * <br>
*  
*/
public class EM_languagetool_True_6_Test {

    
    private static final SutHandler controller = new em.external.org.languagetool.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "languagetool-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exec/languagetool__wbEnabledFlakiness__10210__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_8"));
    private static String baseUrlOfSut;
    
    
    @BeforeClass
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterClass
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @Before
    public void initTest() {
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_0_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_173_getMode
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=InO2c5Tt6G&language=N7FdD%C2%80jJjr&altLanguages=_EM_1192_XYZ_&motherTongue=PiF10oCxo9LK&preferredVariants=.T%5CYoMkxYq5%7CJ&enabledRules=DdfyLwtI7YW&disabledRules=MnLZ&enabledCategories=&disabledCategories=dfQXJzjoMImP43pF&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=nVTpP73T67Ri&" + 
                    "instanceId=_EM_4395_XYZ_&" + 
                    "inputLogging=E&" + 
                    "apiKey=HhFIXW&" + 
                    "tokenV2=6r_AVdMW&" + 
                    "level=default&" + 
                    "v=OV_LC2y&" + 
                    "useragent=ZQ0lte00ZwWJpQM&" + 
                    "username=rf")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_173_getMode
                .assertThat()
                .body(containsString("Error: Internal Error: sqlSessionFactory not initialized - has the database been configured?"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_1_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_191_getLevel
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=NbaGxugpwSnl&language=N7FdDxjDjr&altLanguages=9xJqA&motherTongue=PijKC_waKCvTft&preferredVariants=0T%5CYoMkyYq5zI&enabledRules=DdfyLwtI7UW&disabledRules=_EM_1145_XYZ_&enabledCategories=iPMj6w&disabledCategories=_EM_3462_XYZ_")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=textLevelOnly&" + 
                    "instanceId=wM&" + 
                    "inputLogging=no&" + 
                    "apiKey=zEsuGjOxdna6H8&" + 
                    "tokenV2=_EM_3472_XYZ_&" + 
                    "level=HncLd_K_iQYS&" + 
                    "v=Q&" + 
                    "useragent=_EM_3465_XYZ_&" + 
                    "username=WcRT8bPWT4VCKa0")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_191_getLevel
                .assertThat()
                .body(containsString("Error: Internal Error: sqlSessionFactory not initialized - has the database been configured?"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_2_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_173_getMode
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_1845_XYZ_&language=rXs6lWNnK06j&motherTongue=_EM_1846_XYZ_&disabledRules=sC6Oay&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "tokenV2=_EM_1849_XYZ_&" + 
                    "ruleValues=gNc5B4&" + 
                    "mode=da&" + 
                    "password=ZG4xzB9y4Foz&" + 
                    "preferredLanguages=rXs6lWNnK06j&" + 
                    "username=rV8SLq9S")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_173_getMode
                .assertThat()
                .body(containsString("Error: Internal Error: You specified a 'token' parameter but this server doesn't accept tokens"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_3_postOnV2CheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ApiV2_153_handleCheckRequest
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("data=m1G6CZnD_Z&language=bshm9Q8Yx2FMlWe&enabledCategories=_EM_79_XYZ_")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(500)// org/languagetool/server/ApiV2_153_handleCheckRequest
                .assertThat()
                .body(containsString("Error: Internal Error: Unrecognized token 'm1G6CZnD_Z': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')\n at [Source: (String)\"m1G6CZnD_Z\"; line: 1, column: 11]"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_4_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_191_getLevel
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=XqPgQbRJEpB&language=d94X5biz1_lKpVR&altLanguages=_EM_1746_XYZ_&enabledRules=mpa52mKDqN&enabledCategories=C3kY&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=_EM_1749_XYZ_&" + 
                    "level=iCEhEeN0C5_kj_&" + 
                    "ruleValues=OxT&" + 
                    "useragent=WX&" + 
                    "noopLanguages=VT7SDp1EMm&" + 
                    "token=ZRlEpDmo3bIZCe&" + 
                    "mode=DnrCwyuXWm&" + 
                    "password=Y4YVIVG&" + 
                    "filterDictionaryMatches=_EM_1751_XYZ_&" + 
                    "textSessionId=XqPgQbRJEpB")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_191_getLevel
                .assertThat()
                .body(containsString("Error: Internal Error: You specified a 'token' parameter but this server doesn't accept tokens"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_5_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/UserLimits_71_getLimitsFromToken
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_313_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_320_XYZ_&language=mPFxQqqOzTFQ&altLanguages=LR&motherTongue=a81Qc23C&preferredVariants=FiUxVn&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "inputLogging=51z0RM21L&" + 
                    "tokenV2=_EM_323_XYZ_&" + 
                    "ruleValues=rOSVppSg9xGfQZFa&" + 
                    "useragent=_EM_324_XYZ_&" + 
                    "token=_EM_325_XYZ_&" + 
                    "instanceId=LKQw3MdyGU&" + 
                    "filterDictionaryMatches=v2Hto0rC6XebC8Z&" + 
                    "textSessionId=_EM_328_XYZ_")
                .then()
                .statusCode(500)// org/languagetool/server/UserLimits_71_getLimitsFromToken
                .assertThat()
                .body(containsString("Error: Internal Error: You specified a 'token' parameter but this server doesn't accept tokens"));
    }
    
    
    /**
    * Calls:
    * (500) POST:/v2/check
    * Found 2 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_6_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault100. HTTP Status 500. org/languagetool/server/DatabaseAccess_187_getUserId
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=HUO2c5Tt6G&language=N7FdD%C2%80jLjr&altLanguages=_EM_1192_XYZ_&motherTongue=PiF10oCyo9LK&preferredVariants=_EM_3718_XYZ_&enabledRules=DdfyLwtI7YW&disabledRules=8k&enabledCategories=_EM_3719_XYZ_&disabledCategories=dfQXJzjoMImP43pF&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "mode=all&" + 
                    "instanceId=_EM_3720_XYZ_&" + 
                    "inputLogging=CLm&" + 
                    "apiKey=Irc&" + 
                    "tokenV2=_EM_1196_XYZ_&" + 
                    "level=default&" + 
                    "v=__CyoGjL&" + 
                    "useragent=_EM_4387_XYZ_&" + 
                    "username=ti")
                .then()
                .statusCode(500)// org/languagetool/server/DatabaseAccess_187_getUserId
                .assertThat()
                .body(containsString("Error: Internal Error: sqlSessionFactory not initialized - has the database been configured?"));
    }
    
    
    /**
    * Calls:
    * 1 - (400) POST:/v2/check
    * 2 - (500) POST:/v2/check
    * Found 3 potential faults. Type-codes: 100, 101
    */
    @Test(timeout = 60000)
    public void test_7_postOnCheckShowsFaults_100_101() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=uie&language=_EM_1842_XYZ_")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_1842_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
        
        // Fault100. HTTP Status 500. org/languagetool/server/ServerTools_173_getMode
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 500 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_1845_XYZ_&language=rXs6lWNnK06j&motherTongue=_EM_1846_XYZ_&disabledRules=sC6Oay&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "tokenV2=_EM_1849_XYZ_&" + 
                    "ruleValues=gNc5B4&" + 
                    "mode=da&" + 
                    "password=ZG4xzB9y4Foz&" + 
                    "preferredLanguages=rXs6lWNnK06j&" + 
                    "username=rV8SLq9S")
                .then()
                .statusCode(500)// org/languagetool/server/ServerTools_173_getMode
                .assertThat()
                .body(containsString("Error: Internal Error: You specified a 'token' parameter but this server doesn't accept tokens"));
    }
    
    
    /**
    * Calls:
    * (200) GET:/v2/languages
    */
    @Test(timeout = 60000)
    public void test_8_getOnLanguagesReturns44Elements() throws Exception {
        
        given().accept("application/json")
                .header("x-EMextraHeader123", "")
                .get(baseUrlOfSut + "/v2/languages?EMextraParam123=42")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("size()", equalTo(44))
                .body("[0].'name'", containsString("Arabic"))
                .body("[0].'code'", containsString("ar"))
                .body("[0].'longCode'", containsString("ar"))
                .body("[1].'name'", containsString("Asturian"))
                .body("[1].'code'", containsString("ast"))
                .body("[1].'longCode'", containsString("ast-ES"))
                .body("[2].'name'", containsString("Belarusian"))
                .body("[2].'code'", containsString("be"))
                .body("[2].'longCode'", containsString("be-BY"))
                ; // Skipping assertions on the remaining 41 elements. This limit of 3 elements can be increased in the configurations
    }
    
    
    /**
    * Calls:
    * (200) GET:/v2/swagger
    */
    @Test(timeout = 60000)
    public void test_9_getOnSwaggerReturnsObject() throws Exception {
        
        given().accept("*/*")
                .get(baseUrlOfSut + "/v2/swagger")
                .then()
                .statusCode(200);
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_10_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_1988_XYZ_&language=EN&altLanguages=ku2tGtKLT&motherTongue=ZH&enabledRules=_EM_343_XYZ_&disabledRules=7BaFB&enabledCategories=_EM_345_XYZ_&disabledCategories=cmRiJo2Tllk&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'ku2tGtKLT' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_11_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=5vjnSdzFbmS&language=EN&altLanguages=ku2tGtKLT&motherTongue=ZH&enabledRules=wQQbfZm&disabledRules=6BaCB&enabledCategories=DzAKBnV%7E5&disabledCategories=k8vAXb28tKszY9D&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'ku2tGtKLT' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_12_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/x-www-form-urlencoded")
                .body("text=5vjnSdzFbmSM&language=auto&altLanguages=ku2tGtKLT&motherTongue=_EM_341_XYZ_&enabledRules=_EM_343_XYZ_&disabledRules=_EM_1383_XYZ_&disabledCategories=tFrTCi96GrgE&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_341_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_13_postOnV2CheckWithQueryParamsEmptyDisabledReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("language=TK3JAb0YVhP0QO&altLanguages=xmKw11ECMWKAStU&enabledRules=_EM_918_XYZ_&disabledRules=3KBHhQREKj8UGfNY")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=JfGC3EWxw8AXXgSf&" + 
                    "level=_EM_922_XYZ_&" + 
                    "ruleValues=iMI1tHI7&" + 
                    "useragent=_EM_923_XYZ_&" + 
                    "noopLanguages=_EM_924_XYZ_&" + 
                    "enabled=1i6_d_qQ&" + 
                    "password=UoKebZPVyyLiRgi&" + 
                    "autodetect=vD_VVB&" + 
                    "filterDictionaryMatches=_EM_927_XYZ_&" + 
                    "v=i2Q7&" + 
                    "preferredLanguages=_EM_929_XYZ_&" + 
                    "textSessionId=_EM_930_XYZ_&" + 
                    "disabled=&" + 
                    "username=_EM_931_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Missing 'text' or 'data' parameter"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_14_postOnV2CheckWithQueryParamsEmptyModeReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_4_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("text=gWGgIdw3lQX7fo1&data=Eitv&language=_EM_1017_XYZ_&altLanguages=l0Xmn_T&motherTongue=9&preferredVariants=U6_7yzJojWpF4&disabledRules=_EM_2_XYZ_&enabledCategories=nxFI&disabledCategories=U1Dj&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "EMextraParam123=42&" + 
                    "apiKey=_EM_1334_XYZ_&" + 
                    "inputLogging=UUMzJ5oU&" + 
                    "tokenV2=kADC7V3&" + 
                    "level=picky&" + 
                    "ruleValues=M8qhD7dX4y&" + 
                    "useragent=_EM_1339_XYZ_&" + 
                    "noopLanguages=TFXPiSRDshJFoT_C&" + 
                    "enabled=_EM_1151_XYZ_&" + 
                    "token=R%3D&" + 
                    "mode=&" + 
                    "password=ZNm1vtkEqjVTq&" + 
                    "autodetect=icip8uk&" + 
                    "instanceId=_EM_1340_XYZ_&" + 
                    "filterDictionaryMatches=_EM_1025_XYZ_&" + 
                    "v=_EM_1153_XYZ_&" + 
                    "preferredLanguages=_EM_1154_XYZ_&" + 
                    "textSessionId=NvvuC673Okjy&" + 
                    "disabled=JuoKa1kaz&" + 
                    "username=CnPv9nRJ9")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Set only 'text' or 'data' parameter, not both"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_15_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_31_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("text=bpiu9yNw99cZI8T&language=_EM_38_XYZ_&motherTongue=_EM_39_XYZ_&preferredVariants=_EM_40_XYZ_&disabledRules=_EM_41_XYZ_&enabledCategories=_EM_42_XYZ_&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "EMextraParam123=42&" + 
                    "apiKey=oTFVAYBGU00P&" + 
                    "inputLogging=_EM_43_XYZ_&" + 
                    "tokenV2=_EM_44_XYZ_&" + 
                    "level=_EM_45_XYZ_&" + 
                    "useragent=_EM_47_XYZ_&" + 
                    "noopLanguages=aqZb2&" + 
                    "token=_EM_48_XYZ_&" + 
                    "password=_EM_50_XYZ_&" + 
                    "autodetect=_EM_51_XYZ_&" + 
                    "instanceId=_EM_52_XYZ_&" + 
                    "filterDictionaryMatches=_EM_53_XYZ_&" + 
                    "textSessionId=_EM_55_XYZ_&" + 
                    "disabled=_EM_56_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'disabled' but the parameter is now called 'disabledRules' in v2 of the API"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_16_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=cAh&language=Pu&motherTongue=R6gIeIWWE&enabledRules=AxjPn0et0&disabledRules=_EM_264_XYZ_")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=0WrtFpemq1CJj&" + 
                    "inputLogging=_EM_2323_XYZ_&" + 
                    "tokenV2=KUUTUq0VDSU9&" + 
                    "level=picky&" + 
                    "ruleValues=IeYgPYGDIrKBO9u&" + 
                    "useragent=0&" + 
                    "noopLanguages=_EM_2320_XYZ_&" + 
                    "enabled=_EM_2324_XYZ_&" + 
                    "token=qN4Z47MOZaNGEoEd&" + 
                    "mode=_EM_2325_XYZ_&" + 
                    "password=1grha&" + 
                    "autodetect=tf&" + 
                    "instanceId=Wl9Uq1IyK6_IOREQ&" + 
                    "filterDictionaryMatches=zq0Lk1K&" + 
                    "v=UEKUU3U1_UUb_&" + 
                    "preferredLanguages=IKt7h5oOdvoYIw&" + 
                    "textSessionId=NUr%3FXUFUVTJjSUU&" + 
                    "disabled=_EM_2326_XYZ_&" + 
                    "username=Lfni0tM9zFeATi")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'enabled' but the parameter is now called 'enabledRules' in v2 of the API"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_17_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_156_XYZ_&language=_EM_158_XYZ_&altLanguages=_EM_159_XYZ_&motherTongue=ytsku4N3oOcc&disabledRules=_EM_161_XYZ_&disabledCategories=AUSWbws&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=_EM_163_XYZ_&" + 
                    "level=S0oavGgaA92h94f7&" + 
                    "ruleValues=FXWQI&" + 
                    "useragent=OkmGx9IFRHRm55&" + 
                    "mode=9sHea&" + 
                    "instanceId=dc&" + 
                    "filterDictionaryMatches=4&" + 
                    "preferredLanguages=_EM_168_XYZ_&" + 
                    "textSessionId=_EM_169_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: apiKey was set, but username was not: _EM_163_XYZ_"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_18_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=6Y5z&language=&altLanguages=_EM_1269_XYZ_&preferredVariants=02bY5e&disabledRules=_EM_1272_XYZ_&disabledCategories=_EM_1273_XYZ_")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Missing 'language' parameter, e.g. 'language=en-US' for American English or 'language=fr' for French"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_19_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_475_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("data=&language=_EM_469_XYZ_&motherTongue=_EM_470_XYZ_&enabledRules=VndJYHX1D&enabledCategories=_EM_472_XYZ_&disabledCategories=_EM_473_XYZ_")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=_EM_474_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'data' key in JSON requires 'text' or 'annotation' key"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_20_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=2Qh7zmP_8R3LZ&language=_EM_1044_XYZ_&altLanguages=sdz_9awxT3Ib&motherTongue=iMAYNBjm_Bh94S&enabledRules=U1&enabledCategories=_EM_1045_XYZ_&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "EMextraParam123=42&" + 
                    "apiKey=0GCluGeqM9HbQT&" + 
                    "inputLogging=_EM_1047_XYZ_&" + 
                    "ruleValues=RadxBwqhXWU9JFc&" + 
                    "useragent=_EM_1049_XYZ_&" + 
                    "noopLanguages=8wILwjLh32d&" + 
                    "token=pG&" + 
                    "autodetect=_EM_1053_XYZ_&" + 
                    "v=_EM_1055_XYZ_&" + 
                    "username=_EM_1057_XYZ_")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'autodetect' but automatic language detection is now activated with 'language=auto' in v2 of the API"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_21_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=gkRzntFNTduLvT6q&language=auto&altLanguages=FFrOPsv_4AHHy&preferredVariants=_EM_1714_XYZ_&enabledRules=_EM_914_XYZ_&disabledRules=ml&enabledCategories=Lsa&disabledCategories=_EM_1715_XYZ_&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Invalid format for 'preferredVariants', expected a dash as in 'en-GB': '_EM_1714_XYZ_'"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_22_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "42")
                .contentType("application/x-www-form-urlencoded")
                .body("text=SwmMVW0ZBn9i&language=vNwNbPWnDtRprl&motherTongue=y&preferredVariants=_EM_81_XYZ_&enabledRules=_EM_82_XYZ_&disabledRules=liw&disabledCategories=5C&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: You specified 'preferredVariants' but you didn't specify 'language=auto'"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_23_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=2&language=N4EIm8g4TLU&motherTongue=Fnc6IIAwmsyPn_Y7&enabledCategories=xf3EuLc&disabledCategories=hmDt&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'N4EIm8g4TLU' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_24_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=5vjnSdzFbmS&language=-x-&altLanguages=ku2tGtKLT&motherTongue=ZH&enabledRules=dug3DaSJNQU3&disabledRules=_EM_1383_XYZ_&disabledCategories=tFrTCi9%26GrgE&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '-x-' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_25_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "_EM_4_XYZ_")
                .contentType("application/x-www-form-urlencoded")
                .body("text=gWGgIdw3lQZ7fo1&data=_EM_1347_XYZ_&language=d&altLanguages=_EM_1_XYZ_&motherTongue=_EM%5D1018_XYZ_5&preferredVariants=U6_7yzJojWpF4&enabledRules=_EM_1348_XYZ_&disabledRules=TdfTHaJ4KNKs&enabledCategories=nxFI&disabledCategories=SFx&enabledOnly=false")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "apiKey=_EM_1349_XYZ_&" + 
                    "inputLogging=_EM_1350_XYZ_&" + 
                    "tokenV2=FyVfdaO&" + 
                    "level=default&" + 
                    "ruleValues=U&" + 
                    "useragent=Jmf47p%60&" + 
                    "noopLanguages=_EM_1023_XYZ_&" + 
                    "enabled=U&" + 
                    "token=VMB&" + 
                    "mode=allButTextLevelOnly&" + 
                    "password=_EM_1342_XYZ_&" + 
                    "autodetect=UsCF&" + 
                    "instanceId=_EM_1343_XYZ_k&" + 
                    "filterDictionaryMatches=XOkniHg&" + 
                    "v=_EM_1344_XYZ_&" + 
                    "preferredLanguages=_EM_1345_XYZ_&" + 
                    "textSessionId=DjWQ8na0eZwXdz5V&" + 
                    "disabled=_EM_1351_XYZ_&" + 
                    "username=agHztgHs%5B")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Set only 'text' or 'data' parameter, not both"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_26_postOnV2CheckWithQueryParamsEmptyUsernameReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=_EM_172_XYZ_&data=_EM_539_XYZ_&language=vNwNbPgnDtRprl&motherTongue=&preferredVariants=_EM_81_XYZ_&enabledRules=Y6rNnzmrT0hh&disabledRules=lhw&enabledCategories=RHYTk8Qvy2iud&disabledCategories=5C&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check?" + 
                    "EMextraParam123=42&" + 
                    "apiKey=_EM_540_XYZ_&" + 
                    "inputLogging=jQyq&" + 
                    "tokenV2=pnyYSz1E5&" + 
                    "level=Mp&" + 
                    "ruleValues=_EM_541_XYZ_&" + 
                    "useragent=b&" + 
                    "enabled=XwdlwRTRE5rt9&" + 
                    "token=SJJ4c&" + 
                    "mode=all&" + 
                    "autodetect=Fk3CwCvv81&" + 
                    "password=_EM_542_XYZ_&" + 
                    "instanceId=_EM_543_XYZ_&" + 
                    "filterDictionaryMatches=bH9UnBfuBrG1s6&" + 
                    "v=6Etd6UM2C&" + 
                    "textSessionId=lT1NOm%252Xm&" + 
                    "disabled=L&" + 
                    "multilingual=cC&" + 
                    "username=")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: Set only 'text' or 'data' parameter, not both"));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_27_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=cAh&language=Pu&motherTongue=T6gIeIWWE&disabledRules=_EM_264_XYZ_")
                .post(baseUrlOfSut + "/v2/check?EMextraParam123=42")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: 'Pu' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_28_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=uie&language=Gl&altLanguages=_EM_1843_XYZ_&disabledRules=_EM_1844_XYZ_")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_1843_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_29_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=JxReqNUOD9badW&language=_EM_1566_XYZ_&motherTongue=19VJZ966&disabledRules=_EM_1569_XYZ_&enabledOnly=true")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_1566_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }
    
    
    /**
    * Calls:
    * (400) POST:/v2/check
    * Found 1 potential fault of type-code 101
    */
    @Test(timeout = 60000)
    public void test_30_postOnCheckReturnsMismatchResponseWithSchema() throws Exception {
        
        // Fault101. Received A Response From API With A Structure/Data That Is Not Matching Its Schema. Type: validation.response.status.unknown Response status 400 not defined for path '/check'.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .contentType("application/x-www-form-urlencoded")
                .body("text=OQJrxUR&language=_EM_2467_XYZ_&altLanguages=tvpxaNzp&motherTongue=HMnUvSB5SZV&disabledRules=_EM_2469_XYZ_")
                .post(baseUrlOfSut + "/v2/check")
                .then()
                .statusCode(400)
                .assertThat()
                .body(containsString("Error: '_EM_2467_XYZ_' is not a language code known to LanguageTool. Supported language codes are: ar, ast-ES, be-BY, br-FR, ca-ES, ca-ES-valencia, da-DK, de, de-AT, de-CH, de-DE, de-DE-x-simple-language, el-GR, en, en-AU, en-CA, en-GB, en-NZ, en-US, en-ZA, eo, es, fa, fr, ga-IE, gl-ES, it, ja-JP, km-KH, pl-PL, pt, pt-AO, pt-BR, pt-MZ, pt-PT, ro-RO, ru-RU, sk-SK, sl-SI, sv, ta-IN, tl-PH, uk-UA, zh-CN. The list of languages is read from META-INF/org/languagetool/language-module.properties in the Java classpath. See https://dev.languagetool.org/java-api for details."));
    }


}
