/**
* LICENSE DISCLAIMER
* This file has been generated by EvoMaster.
* The content of this file is not subject to the license of EvoMaster itself, i.e., LGPL.
* This generated software (i.e., the test suite in this file) can be freely used, modified, 
* and distributed as you see fit without any restrictions.
*/
import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2026-03-04T16:03:58.703639514+08:00[Asia/Shanghai]
 * <br>
*  The generated test suite contains 7 tests
 * <br>
*  Covered targets: 597
 * <br>
*  Used time: 1h 31m 39s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  
*/
public class EM_familie_ba_sak_False_6_Test_6 {

    
    private static final SutHandler controller = new em.external.familie.ba.sak.ExternalEvoMasterController(extractSutJarNameWithEnvVarName("WFD_DIST_DIR", "familie-ba-sak-sut.jar")).setJaCoCo("/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacocoagent.jar","/home/server/workspace/SCY/MicroService/Dataset/jacoco/jacococli.jar","/home/server/workspace/SCY/MicroService/Dataset/exec/familie-ba-sak__wbEnabledFlakiness__10120__jacoco.exec",8899).setJavaCommand(extractJDKPathWithEnvVarName("JAVA_HOME_17"));
    private static String baseUrlOfSut;
    
    
    @BeforeAll
    public static void initClass() {
        controller.setupForGeneratedTest();
        baseUrlOfSut = controller.startSut();
        controller.registerOrExecuteInitSqlCommandsIfNeeded();
        assertNotNull(baseUrlOfSut);
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    @AfterAll
    public static void tearDown() {
        controller.stopSut();
    }
    
    
    @BeforeEach
    public void initTest() {
        controller.resetDatabase(Arrays.asList());
        controller.resetStateOfSUT();
    }
    
    
    
    
    /**
    * Calls:
    * 1 - (403) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 2 - (200) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 3 - (401) GET:/api/task/{id}
    * Found 1 potential fault of type-code 205
    */
    @Test @Timeout(60)
    public void test_0_getOnTaskAuthenticatedButWronglyToldNot() throws Exception {
        
        final String token_TaskRunner = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=TaskRunner&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_TaskRunner = "Bearer " + token_TaskRunner;
        final String token_Veileder = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=Veileder&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_Veileder = "Bearer " + token_Veileder;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("text/html");
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'data'.'INNVILGET'.size()", equalTo(132))
                .body("'data'.'INNVILGET'[0].'navn'", containsString("Norsk, nordisk bosatt i Norge"))
                .body("'data'.'INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'INNVILGET'[1].'navn'", containsString("Tredjelandsborger med lovlig opphold samtidig som bosatt i Norge"))
                .body("'data'.'INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INNVILGET'[2].'navn'", containsString("Tredjelandsborger bosatt før lovlig opphold i Norge"))
                .body("'data'.'INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 129 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'REDUKSJON'.size()", equalTo(72))
                .body("'data'.'REDUKSJON'[0].'navn'", containsString("Barn har flyttet fra Norge"))
                .body("'data'.'REDUKSJON'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'REDUKSJON'[1].'navn'", containsString("Barn har ikke oppholdstillatelse"))
                .body("'data'.'REDUKSJON'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'REDUKSJON'[2].'navn'", containsString("Barn har flyttet fra søker (flytting mellom foreldre, andre omsorgspersoner)"))
                .body("'data'.'REDUKSJON'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 69 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'AVSLAG'.size()", equalTo(64))
                .body("'data'.'AVSLAG'[0].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'AVSLAG'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'AVSLAG'[1].'navn'", containsString("Tredjelandsborger uten lovlig opphold "))
                .body("'data'.'AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'AVSLAG'[2].'navn'", containsString("Barn bor ikke med søker\t"))
                .body("'data'.'AVSLAG'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 61 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'OPPHØR'.size()", equalTo(51))
                .body("'data'.'OPPHØR'[0].'navn'", containsString("Barn bor ikke med søker"))
                .body("'data'.'OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'OPPHØR'[1].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'OPPHØR'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'OPPHØR'[2].'navn'", containsString("Et barn er dødt"))
                .body("'data'.'OPPHØR'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 48 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'FORTSATT_INNVILGET'.size()", equalTo(50))
                .body("'data'.'FORTSATT_INNVILGET'[0].'navn'", containsString("Søker og barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'navn'", containsString("Søker oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'navn'", containsString("Barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'vilkår'", containsString("BOSATT_I_RIKET"))
                // Skipping assertions on the remaining 47 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ENDRET_UTBETALING'.size()", equalTo(16))
                .body("'data'.'ENDRET_UTBETALING'[0].'navn'", containsString("Delt bosted ingen utbetaling"))
                .body("'data'.'ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[1].'navn'", containsString("Delt bosted full utbetaling før søknad"))
                .body("'data'.'ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[2].'navn'", containsString("Delt bosted - får kun etterbetalt utvidet"))
                .body("'data'.'ENDRET_UTBETALING'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 13 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ETTER_ENDRET_UTBETALING'.size()", equalTo(6))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'navn'", containsString("Rettsavgjørelse delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'navn'", containsString("Vurdering avtale delt bosted følges"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'navn'", containsString("Avtale delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_INNVILGET'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'navn'", containsString("Bor fast i institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'navn'", containsString("Barn 6 år institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_AVSLAG'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'navn'", containsString("Ikke bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'navn'", containsString("Ikke oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_OPPHØR'.size()", equalTo(6))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'navn'", containsString("Flyttet fra institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'navn'", containsString("Barn død"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'navn'", containsString("Barn bodde ikke fast i institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'.size()", equalTo(4))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'navn'", containsString("Bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'navn'", containsString("Oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'navn'", containsString("Varig oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 1 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'EØS_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_OPPHØR'.size()", equalTo(0))
                .body("'data'.'EØS_AVSLAG'.size()", equalTo(0))
                .body("'data'.'EØS_FORTSATT_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_REDUKSJON'.size()", equalTo(0))
                .body("'status'", containsString("SUKSESS"))
                .body("'melding'", containsString("Innhenting av data var vellykket"))
                .body("'frontendFeilmelding'", nullValue())
                .body("'stacktrace'", nullValue());
        
        // Fault205. Wrongly Not Recognized as Authenticated.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/task/528")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (403) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 2 - (200) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 3 - (401) GET:/api/task/v2
    * Found 1 potential fault of type-code 205
    */
    @Test @Timeout(60)
    public void test_1_getOnV2AuthenticatedButWronglyToldNot() throws Exception {
        
        final String token_TaskRunner = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=TaskRunner&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_TaskRunner = "Bearer " + token_TaskRunner;
        final String token_Veileder = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=Veileder&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_Veileder = "Bearer " + token_Veileder;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("text/html");
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'data'.'INNVILGET'.size()", equalTo(132))
                .body("'data'.'INNVILGET'[0].'navn'", containsString("Norsk, nordisk bosatt i Norge"))
                .body("'data'.'INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'INNVILGET'[1].'navn'", containsString("Tredjelandsborger med lovlig opphold samtidig som bosatt i Norge"))
                .body("'data'.'INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INNVILGET'[2].'navn'", containsString("Tredjelandsborger bosatt før lovlig opphold i Norge"))
                .body("'data'.'INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 129 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'REDUKSJON'.size()", equalTo(72))
                .body("'data'.'REDUKSJON'[0].'navn'", containsString("Barn har flyttet fra Norge"))
                .body("'data'.'REDUKSJON'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'REDUKSJON'[1].'navn'", containsString("Barn har ikke oppholdstillatelse"))
                .body("'data'.'REDUKSJON'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'REDUKSJON'[2].'navn'", containsString("Barn har flyttet fra søker (flytting mellom foreldre, andre omsorgspersoner)"))
                .body("'data'.'REDUKSJON'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 69 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'AVSLAG'.size()", equalTo(64))
                .body("'data'.'AVSLAG'[0].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'AVSLAG'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'AVSLAG'[1].'navn'", containsString("Tredjelandsborger uten lovlig opphold "))
                .body("'data'.'AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'AVSLAG'[2].'navn'", containsString("Barn bor ikke med søker\t"))
                .body("'data'.'AVSLAG'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 61 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'OPPHØR'.size()", equalTo(51))
                .body("'data'.'OPPHØR'[0].'navn'", containsString("Barn bor ikke med søker"))
                .body("'data'.'OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'OPPHØR'[1].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'OPPHØR'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'OPPHØR'[2].'navn'", containsString("Et barn er dødt"))
                .body("'data'.'OPPHØR'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 48 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'FORTSATT_INNVILGET'.size()", equalTo(50))
                .body("'data'.'FORTSATT_INNVILGET'[0].'navn'", containsString("Søker og barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'navn'", containsString("Søker oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'navn'", containsString("Barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'vilkår'", containsString("BOSATT_I_RIKET"))
                // Skipping assertions on the remaining 47 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ENDRET_UTBETALING'.size()", equalTo(16))
                .body("'data'.'ENDRET_UTBETALING'[0].'navn'", containsString("Delt bosted ingen utbetaling"))
                .body("'data'.'ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[1].'navn'", containsString("Delt bosted full utbetaling før søknad"))
                .body("'data'.'ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[2].'navn'", containsString("Delt bosted - får kun etterbetalt utvidet"))
                .body("'data'.'ENDRET_UTBETALING'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 13 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ETTER_ENDRET_UTBETALING'.size()", equalTo(6))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'navn'", containsString("Rettsavgjørelse delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'navn'", containsString("Vurdering avtale delt bosted følges"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'navn'", containsString("Avtale delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_INNVILGET'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'navn'", containsString("Bor fast i institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'navn'", containsString("Barn 6 år institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_AVSLAG'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'navn'", containsString("Ikke bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'navn'", containsString("Ikke oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_OPPHØR'.size()", equalTo(6))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'navn'", containsString("Flyttet fra institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'navn'", containsString("Barn død"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'navn'", containsString("Barn bodde ikke fast i institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'.size()", equalTo(4))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'navn'", containsString("Bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'navn'", containsString("Oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'navn'", containsString("Varig oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 1 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'EØS_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_OPPHØR'.size()", equalTo(0))
                .body("'data'.'EØS_AVSLAG'.size()", equalTo(0))
                .body("'data'.'EØS_FORTSATT_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_REDUKSJON'.size()", equalTo(0))
                .body("'status'", containsString("SUKSESS"))
                .body("'melding'", containsString("Innhenting av data var vellykket"))
                .body("'frontendFeilmelding'", nullValue())
                .body("'stacktrace'", nullValue());
        
        // Fault205. Wrongly Not Recognized as Authenticated.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/task/v2?" + 
                    "status=AVVIKSH%C3%85NDTERT&" + 
                    "page=98")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (403) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 2 - (200) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 3 - (401) GET:/api/task/ferdigNaaFeiletFoer
    * Found 1 potential fault of type-code 205
    */
    @Test @Timeout(60)
    public void test_2_getOnFerdigNaaFeiletFoerAuthenticatedButWronglyToldNot() throws Exception {
        
        final String token_TaskRunner = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=TaskRunner&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_TaskRunner = "Bearer " + token_TaskRunner;
        final String token_Veileder = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=Veileder&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_Veileder = "Bearer " + token_Veileder;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("text/html");
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'data'.'INNVILGET'.size()", equalTo(132))
                .body("'data'.'INNVILGET'[0].'navn'", containsString("Norsk, nordisk bosatt i Norge"))
                .body("'data'.'INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'INNVILGET'[1].'navn'", containsString("Tredjelandsborger med lovlig opphold samtidig som bosatt i Norge"))
                .body("'data'.'INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INNVILGET'[2].'navn'", containsString("Tredjelandsborger bosatt før lovlig opphold i Norge"))
                .body("'data'.'INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 129 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'REDUKSJON'.size()", equalTo(72))
                .body("'data'.'REDUKSJON'[0].'navn'", containsString("Barn har flyttet fra Norge"))
                .body("'data'.'REDUKSJON'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'REDUKSJON'[1].'navn'", containsString("Barn har ikke oppholdstillatelse"))
                .body("'data'.'REDUKSJON'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'REDUKSJON'[2].'navn'", containsString("Barn har flyttet fra søker (flytting mellom foreldre, andre omsorgspersoner)"))
                .body("'data'.'REDUKSJON'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 69 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'AVSLAG'.size()", equalTo(64))
                .body("'data'.'AVSLAG'[0].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'AVSLAG'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'AVSLAG'[1].'navn'", containsString("Tredjelandsborger uten lovlig opphold "))
                .body("'data'.'AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'AVSLAG'[2].'navn'", containsString("Barn bor ikke med søker\t"))
                .body("'data'.'AVSLAG'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 61 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'OPPHØR'.size()", equalTo(51))
                .body("'data'.'OPPHØR'[0].'navn'", containsString("Barn bor ikke med søker"))
                .body("'data'.'OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'OPPHØR'[1].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'OPPHØR'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'OPPHØR'[2].'navn'", containsString("Et barn er dødt"))
                .body("'data'.'OPPHØR'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 48 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'FORTSATT_INNVILGET'.size()", equalTo(50))
                .body("'data'.'FORTSATT_INNVILGET'[0].'navn'", containsString("Søker og barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'navn'", containsString("Søker oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'navn'", containsString("Barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'vilkår'", containsString("BOSATT_I_RIKET"))
                // Skipping assertions on the remaining 47 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ENDRET_UTBETALING'.size()", equalTo(16))
                .body("'data'.'ENDRET_UTBETALING'[0].'navn'", containsString("Delt bosted ingen utbetaling"))
                .body("'data'.'ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[1].'navn'", containsString("Delt bosted full utbetaling før søknad"))
                .body("'data'.'ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[2].'navn'", containsString("Delt bosted - får kun etterbetalt utvidet"))
                .body("'data'.'ENDRET_UTBETALING'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 13 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ETTER_ENDRET_UTBETALING'.size()", equalTo(6))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'navn'", containsString("Rettsavgjørelse delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'navn'", containsString("Vurdering avtale delt bosted følges"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'navn'", containsString("Avtale delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_INNVILGET'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'navn'", containsString("Bor fast i institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'navn'", containsString("Barn 6 år institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_AVSLAG'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'navn'", containsString("Ikke bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'navn'", containsString("Ikke oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_OPPHØR'.size()", equalTo(6))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'navn'", containsString("Flyttet fra institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'navn'", containsString("Barn død"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'navn'", containsString("Barn bodde ikke fast i institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'.size()", equalTo(4))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'navn'", containsString("Bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'navn'", containsString("Oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'navn'", containsString("Varig oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 1 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'EØS_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_OPPHØR'.size()", equalTo(0))
                .body("'data'.'EØS_AVSLAG'.size()", equalTo(0))
                .body("'data'.'EØS_FORTSATT_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_REDUKSJON'.size()", equalTo(0))
                .body("'status'", containsString("SUKSESS"))
                .body("'melding'", containsString("Innhenting av data var vellykket"))
                .body("'frontendFeilmelding'", nullValue())
                .body("'stacktrace'", nullValue());
        
        // Fault205. Wrongly Not Recognized as Authenticated.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/task/ferdigNaaFeiletFoer")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (403) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 2 - (200) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 3 - (401) GET:/api/task/antall-til-oppfolging
    * Found 1 potential fault of type-code 205
    */
    @Test @Timeout(60)
    public void test_3_getOnAntall_til_oppfolgingAuthenticatedButWronglyToldNot() throws Exception {
        
        final String token_TaskRunner = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=TaskRunner&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_TaskRunner = "Bearer " + token_TaskRunner;
        final String token_Veileder = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=Veileder&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_Veileder = "Bearer " + token_Veileder;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("text/html");
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'data'.'INNVILGET'.size()", equalTo(132))
                .body("'data'.'INNVILGET'[0].'navn'", containsString("Norsk, nordisk bosatt i Norge"))
                .body("'data'.'INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'INNVILGET'[1].'navn'", containsString("Tredjelandsborger med lovlig opphold samtidig som bosatt i Norge"))
                .body("'data'.'INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INNVILGET'[2].'navn'", containsString("Tredjelandsborger bosatt før lovlig opphold i Norge"))
                .body("'data'.'INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 129 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'REDUKSJON'.size()", equalTo(72))
                .body("'data'.'REDUKSJON'[0].'navn'", containsString("Barn har flyttet fra Norge"))
                .body("'data'.'REDUKSJON'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'REDUKSJON'[1].'navn'", containsString("Barn har ikke oppholdstillatelse"))
                .body("'data'.'REDUKSJON'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'REDUKSJON'[2].'navn'", containsString("Barn har flyttet fra søker (flytting mellom foreldre, andre omsorgspersoner)"))
                .body("'data'.'REDUKSJON'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 69 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'AVSLAG'.size()", equalTo(64))
                .body("'data'.'AVSLAG'[0].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'AVSLAG'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'AVSLAG'[1].'navn'", containsString("Tredjelandsborger uten lovlig opphold "))
                .body("'data'.'AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'AVSLAG'[2].'navn'", containsString("Barn bor ikke med søker\t"))
                .body("'data'.'AVSLAG'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 61 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'OPPHØR'.size()", equalTo(51))
                .body("'data'.'OPPHØR'[0].'navn'", containsString("Barn bor ikke med søker"))
                .body("'data'.'OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'OPPHØR'[1].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'OPPHØR'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'OPPHØR'[2].'navn'", containsString("Et barn er dødt"))
                .body("'data'.'OPPHØR'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 48 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'FORTSATT_INNVILGET'.size()", equalTo(50))
                .body("'data'.'FORTSATT_INNVILGET'[0].'navn'", containsString("Søker og barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'navn'", containsString("Søker oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'navn'", containsString("Barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'vilkår'", containsString("BOSATT_I_RIKET"))
                // Skipping assertions on the remaining 47 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ENDRET_UTBETALING'.size()", equalTo(16))
                .body("'data'.'ENDRET_UTBETALING'[0].'navn'", containsString("Delt bosted ingen utbetaling"))
                .body("'data'.'ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[1].'navn'", containsString("Delt bosted full utbetaling før søknad"))
                .body("'data'.'ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[2].'navn'", containsString("Delt bosted - får kun etterbetalt utvidet"))
                .body("'data'.'ENDRET_UTBETALING'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 13 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ETTER_ENDRET_UTBETALING'.size()", equalTo(6))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'navn'", containsString("Rettsavgjørelse delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'navn'", containsString("Vurdering avtale delt bosted følges"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'navn'", containsString("Avtale delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_INNVILGET'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'navn'", containsString("Bor fast i institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'navn'", containsString("Barn 6 år institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_AVSLAG'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'navn'", containsString("Ikke bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'navn'", containsString("Ikke oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_OPPHØR'.size()", equalTo(6))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'navn'", containsString("Flyttet fra institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'navn'", containsString("Barn død"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'navn'", containsString("Barn bodde ikke fast i institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'.size()", equalTo(4))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'navn'", containsString("Bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'navn'", containsString("Oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'navn'", containsString("Varig oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 1 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'EØS_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_OPPHØR'.size()", equalTo(0))
                .body("'data'.'EØS_AVSLAG'.size()", equalTo(0))
                .body("'data'.'EØS_FORTSATT_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_REDUKSJON'.size()", equalTo(0))
                .body("'status'", containsString("SUKSESS"))
                .body("'melding'", containsString("Innhenting av data var vellykket"))
                .body("'frontendFeilmelding'", nullValue())
                .body("'stacktrace'", nullValue());
        
        // Fault205. Wrongly Not Recognized as Authenticated.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/task/antall-til-oppfolging")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (403) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 2 - (200) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 3 - (401) GET:/api/task/logg/{id}
    * Found 1 potential fault of type-code 205
    */
    @Test @Timeout(60)
    public void test_4_getOnLoggAuthenticatedButWronglyToldNot() throws Exception {
        
        final String token_TaskRunner = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=TaskRunner&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_TaskRunner = "Bearer " + token_TaskRunner;
        final String token_Veileder = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=Veileder&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_Veileder = "Bearer " + token_Veileder;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("text/html");
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'data'.'INNVILGET'.size()", equalTo(132))
                .body("'data'.'INNVILGET'[0].'navn'", containsString("Norsk, nordisk bosatt i Norge"))
                .body("'data'.'INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'INNVILGET'[1].'navn'", containsString("Tredjelandsborger med lovlig opphold samtidig som bosatt i Norge"))
                .body("'data'.'INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INNVILGET'[2].'navn'", containsString("Tredjelandsborger bosatt før lovlig opphold i Norge"))
                .body("'data'.'INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 129 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'REDUKSJON'.size()", equalTo(72))
                .body("'data'.'REDUKSJON'[0].'navn'", containsString("Barn har flyttet fra Norge"))
                .body("'data'.'REDUKSJON'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'REDUKSJON'[1].'navn'", containsString("Barn har ikke oppholdstillatelse"))
                .body("'data'.'REDUKSJON'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'REDUKSJON'[2].'navn'", containsString("Barn har flyttet fra søker (flytting mellom foreldre, andre omsorgspersoner)"))
                .body("'data'.'REDUKSJON'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 69 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'AVSLAG'.size()", equalTo(64))
                .body("'data'.'AVSLAG'[0].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'AVSLAG'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'AVSLAG'[1].'navn'", containsString("Tredjelandsborger uten lovlig opphold "))
                .body("'data'.'AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'AVSLAG'[2].'navn'", containsString("Barn bor ikke med søker\t"))
                .body("'data'.'AVSLAG'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 61 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'OPPHØR'.size()", equalTo(51))
                .body("'data'.'OPPHØR'[0].'navn'", containsString("Barn bor ikke med søker"))
                .body("'data'.'OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'OPPHØR'[1].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'OPPHØR'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'OPPHØR'[2].'navn'", containsString("Et barn er dødt"))
                .body("'data'.'OPPHØR'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 48 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'FORTSATT_INNVILGET'.size()", equalTo(50))
                .body("'data'.'FORTSATT_INNVILGET'[0].'navn'", containsString("Søker og barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'navn'", containsString("Søker oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'navn'", containsString("Barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'vilkår'", containsString("BOSATT_I_RIKET"))
                // Skipping assertions on the remaining 47 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ENDRET_UTBETALING'.size()", equalTo(16))
                .body("'data'.'ENDRET_UTBETALING'[0].'navn'", containsString("Delt bosted ingen utbetaling"))
                .body("'data'.'ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[1].'navn'", containsString("Delt bosted full utbetaling før søknad"))
                .body("'data'.'ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[2].'navn'", containsString("Delt bosted - får kun etterbetalt utvidet"))
                .body("'data'.'ENDRET_UTBETALING'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 13 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ETTER_ENDRET_UTBETALING'.size()", equalTo(6))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'navn'", containsString("Rettsavgjørelse delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'navn'", containsString("Vurdering avtale delt bosted følges"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'navn'", containsString("Avtale delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_INNVILGET'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'navn'", containsString("Bor fast i institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'navn'", containsString("Barn 6 år institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_AVSLAG'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'navn'", containsString("Ikke bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'navn'", containsString("Ikke oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_OPPHØR'.size()", equalTo(6))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'navn'", containsString("Flyttet fra institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'navn'", containsString("Barn død"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'navn'", containsString("Barn bodde ikke fast i institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'.size()", equalTo(4))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'navn'", containsString("Bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'navn'", containsString("Oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'navn'", containsString("Varig oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 1 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'EØS_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_OPPHØR'.size()", equalTo(0))
                .body("'data'.'EØS_AVSLAG'.size()", equalTo(0))
                .body("'data'.'EØS_FORTSATT_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_REDUKSJON'.size()", equalTo(0))
                .body("'status'", containsString("SUKSESS"))
                .body("'melding'", containsString("Innhenting av data var vellykket"))
                .body("'frontendFeilmelding'", nullValue())
                .body("'stacktrace'", nullValue());
        
        // Fault205. Wrongly Not Recognized as Authenticated.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/task/logg/914")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (403) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 2 - (200) GET:/api/vilkaarsvurdering/vilkaarsbegrunnelser
    * 3 - (401) GET:/api/task/callId/{callId}
    * Found 1 potential fault of type-code 205
    */
    @Test @Timeout(60)
    public void test_5_getOnCallIdAuthenticatedButWronglyToldNot() throws Exception {
        
        final String token_TaskRunner = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=TaskRunner&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_TaskRunner = "Bearer " + token_TaskRunner;
        final String token_Veileder = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=Veileder&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_Veileder = "Bearer " + token_Veileder;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(403)
                .assertThat()
                .contentType("text/html");
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/vilkaarsvurdering/vilkaarsbegrunnelser")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'data'.'INNVILGET'.size()", equalTo(132))
                .body("'data'.'INNVILGET'[0].'navn'", containsString("Norsk, nordisk bosatt i Norge"))
                .body("'data'.'INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'INNVILGET'[1].'navn'", containsString("Tredjelandsborger med lovlig opphold samtidig som bosatt i Norge"))
                .body("'data'.'INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INNVILGET'[2].'navn'", containsString("Tredjelandsborger bosatt før lovlig opphold i Norge"))
                .body("'data'.'INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 129 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'REDUKSJON'.size()", equalTo(72))
                .body("'data'.'REDUKSJON'[0].'navn'", containsString("Barn har flyttet fra Norge"))
                .body("'data'.'REDUKSJON'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'REDUKSJON'[1].'navn'", containsString("Barn har ikke oppholdstillatelse"))
                .body("'data'.'REDUKSJON'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'REDUKSJON'[2].'navn'", containsString("Barn har flyttet fra søker (flytting mellom foreldre, andre omsorgspersoner)"))
                .body("'data'.'REDUKSJON'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 69 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'AVSLAG'.size()", equalTo(64))
                .body("'data'.'AVSLAG'[0].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'AVSLAG'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'AVSLAG'[1].'navn'", containsString("Tredjelandsborger uten lovlig opphold "))
                .body("'data'.'AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'AVSLAG'[2].'navn'", containsString("Barn bor ikke med søker\t"))
                .body("'data'.'AVSLAG'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 61 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'OPPHØR'.size()", equalTo(51))
                .body("'data'.'OPPHØR'[0].'navn'", containsString("Barn bor ikke med søker"))
                .body("'data'.'OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'OPPHØR'[1].'navn'", containsString("Ikke bosatt i Norge"))
                .body("'data'.'OPPHØR'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'OPPHØR'[2].'navn'", containsString("Et barn er dødt"))
                .body("'data'.'OPPHØR'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 48 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'FORTSATT_INNVILGET'.size()", equalTo(50))
                .body("'data'.'FORTSATT_INNVILGET'[0].'navn'", containsString("Søker og barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'navn'", containsString("Søker oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[1].'vilkår'", containsString("BOSATT_I_RIKET"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'navn'", containsString("Barn oppholder seg i Norge"))
                .body("'data'.'FORTSATT_INNVILGET'[2].'vilkår'", containsString("BOSATT_I_RIKET"))
                // Skipping assertions on the remaining 47 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ENDRET_UTBETALING'.size()", equalTo(16))
                .body("'data'.'ENDRET_UTBETALING'[0].'navn'", containsString("Delt bosted ingen utbetaling"))
                .body("'data'.'ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[1].'navn'", containsString("Delt bosted full utbetaling før søknad"))
                .body("'data'.'ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ENDRET_UTBETALING'[2].'navn'", containsString("Delt bosted - får kun etterbetalt utvidet"))
                .body("'data'.'ENDRET_UTBETALING'[2].'vilkår'", nullValue())
                // Skipping assertions on the remaining 13 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'ETTER_ENDRET_UTBETALING'.size()", equalTo(6))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'navn'", containsString("Rettsavgjørelse delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[0].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'navn'", containsString("Vurdering avtale delt bosted følges"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[1].'vilkår'", nullValue())
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'navn'", containsString("Avtale delt bosted"))
                .body("'data'.'ETTER_ENDRET_UTBETALING'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_INNVILGET'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'navn'", containsString("Bor fast i institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_INNVILGET'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'navn'", containsString("Barn 6 år institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[0].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'navn'", containsString("Satsendring institusjon"))
                .body("'data'.'INSTITUSJON_REDUKSJON'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_AVSLAG'.size()", equalTo(2))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'navn'", containsString("Ikke bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'navn'", containsString("Ikke oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_AVSLAG'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_OPPHØR'.size()", equalTo(6))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'navn'", containsString("Flyttet fra institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'navn'", containsString("Barn død"))
                .body("'data'.'INSTITUSJON_OPPHØR'[1].'vilkår'", nullValue())
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'navn'", containsString("Barn bodde ikke fast i institusjon"))
                .body("'data'.'INSTITUSJON_OPPHØR'[2].'vilkår'", containsString("BOR_MED_SØKER"))
                // Skipping assertions on the remaining 3 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'.size()", equalTo(4))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'navn'", containsString("Bosatt i institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[0].'vilkår'", containsString("BOR_MED_SØKER"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'navn'", containsString("Oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[1].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'navn'", containsString("Varig oppholdstillatelse institusjon"))
                .body("'data'.'INSTITUSJON_FORTSATT_INNVILGET'[2].'vilkår'", containsString("LOVLIG_OPPHOLD"))
                // Skipping assertions on the remaining 1 elements. This limit of 3 elements can be increased in the configurations
                .body("'data'.'EØS_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_OPPHØR'.size()", equalTo(0))
                .body("'data'.'EØS_AVSLAG'.size()", equalTo(0))
                .body("'data'.'EØS_FORTSATT_INNVILGET'.size()", equalTo(0))
                .body("'data'.'EØS_REDUKSJON'.size()", equalTo(0))
                .body("'status'", containsString("SUKSESS"))
                .body("'melding'", containsString("Innhenting av data var vellykket"))
                .body("'frontendFeilmelding'", nullValue())
                .body("'stacktrace'", nullValue());
        
        // Fault205. Wrongly Not Recognized as Authenticated.
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Veileder) // Veileder
                .get(baseUrlOfSut + "/api/task/callId/IRS")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/html");
    }
    
    
    /**
    * Calls:
    * 1 - (401) GET:/api/task/logg/{id}
    * 2 - (200) GET:/api/task/logg/{id}
    * 3 - (401) GET:/api/ekstern/pensjon/bestill-personer-med-barnetrygd/{år}
    * Found 1 potential fault of type-code 205
    */
    @Test @Timeout(60)
    public void test_6_getOnBestill_personer_med_barnetrygdAuthenticatedButWronglyToldNot() throws Exception {
        
        final String token_Kode6 = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=Kode6&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_Kode6 = "Bearer " + token_Kode6;
        final String token_TaskRunner = given()
                .contentType("application/x-www-form-urlencoded")
                .body("name=TaskRunner&grant_type=client_credentials&code=foo&client_id=foo&client_secret=secret")
                .post("http://localhost:10122/azuread/token")
                .then().extract().response().path("access_token");
                
        final String auth_TaskRunner = "Bearer " + token_TaskRunner;
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_Kode6) // Kode6
                .get(baseUrlOfSut + "/api/task/logg/924?page=706")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/html");
        
        given().accept("*/*")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/task/logg/610")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'data'", nullValue())
                .body("'status'", containsString("FEILET"))
                .body("'melding'", containsString("Henting av tasklogg feilet."))
                .body("'frontendFeilmelding'", containsString("Henting av tasklogg feilet."));
        
        // Fault205. Wrongly Not Recognized as Authenticated.
        given().accept("text/plain")
                .header("x-EMextraHeader123", "")
                .header("Authorization", auth_TaskRunner) // TaskRunner
                .get(baseUrlOfSut + "/api/ekstern/pensjon/bestill-personer-med-barnetrygd/910")
                .then()
                .statusCode(401)
                .assertThat()
                .contentType("text/plain")
                .body(containsString("HTTP ERROR 401 Pensjon tjeneste kan kun kalles av pensjon eller innlogget bruker med FORVALTER rolle\nURI: /api/ekstern/pensjon/bestill-personer-med-barnetrygd/910\nSTATUS: 401\nMESSAGE: Pensjon tjeneste kan kun kalles av pensjon eller innlogget bruker med FORVALTER rolle\nSERVLET: dispatcherServlet\n"));
    }


}
